Repository kubernetes-sigs/kwok, pull requests merged in 2022-09, with the labels that each got.

#14 improve: test
  pkg/controllers/node_controller_test.go
  pkg/controllers/pod_controller_test.go
Labels: ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#31 Change used image to registry.k8s.io
  .github/workflows/releases.yaml
Labels: kind/feature, approved, size/S, cncf-cla: yes, lgtm

#37 Add KWOK_MODE to configure several default cluster templates
  pkg/kwokctl/vars/vars.go
Labels: kind/bug, kind/feature, approved, size/S, cncf-cla: yes, lgtm

#38 Update FeatureGate when Bump Release
  hack/supported_releases.sh
  pkg/kwokctl/k8s/feature_gates.go
  pkg/kwokctl/k8s/feature_gates_data.sh
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M

#40 Maintains only the latest 6 releases
  Makefile
  hack/supported_releases.sh
  supported_releases.txt
Labels: kind/feature, approved, size/S, cncf-cla: yes

#43 Prompt before start downloading
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/utils/download.go
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#45 Reduce the magnitude of benchmark
  test/kwokctl/kwokctl_benchmark_test.sh
Labels: approved, size/XS, cncf-cla: yes, lgtm, kind/flake

#44 Fix symlink
  pkg/kwokctl/utils/download.go
Labels: kind/bug, approved, size/XS, cncf-cla: yes, lgtm

#42 🐛reuse kubectl found in path
  pkg/kwokctl/runtime/cluster.go
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm

#47 Fix reuse kubectl
  pkg/kwokctl/runtime/cluster.go
Labels: kind/bug, approved, size/XS, cncf-cla: yes, lgtm
