Repository kubernetes-sigs/kwok, pull requests merged in 2022-08, with the labels that each got.

#1 First commit
  .gitignore
  cmd/controller/main.go
  go.mod
  go.sum
  images/kwok/Dockerfile
  images/kwok/build.sh
  kustomize/controller/controller-clusterrole.yaml
  kustomize/controller/controller-clusterrolebinding.yaml
  kustomize/controller/controller-deployment.yaml
  kustomize/controller/controller-serviceaccount.yaml
  kustomize/controller/kustomization.yaml
  pkg/controllers/controller.go
  pkg/controllers/node_controller.go
  pkg/controllers/node_controller_test.go
  pkg/controllers/pod_controller.go
  pkg/controllers/pod_controller_test.go
  pkg/controllers/templates/node.heartbeat.tpl
  pkg/controllers/templates/node.status.tpl
  pkg/controllers/templates/pod.status.tpl
  pkg/controllers/templates/templates.go
  pkg/controllers/utils.go
  pkg/controllers/utils_test.go
  pkg/logger/logger.go
  test/controller/controller.test.sh
  test/controller/fake-deployment.yaml
  test/controller/fake-node.yaml
  test/controller/kustomization.yaml
Labels: size/XXL, approved, cncf-cla: yes, lgtm

#7 Makefile to organize CI jobs
  .gitignore
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#11 Rename controller to kwok and add ci
  Makefile
  cmd/kwok/main.go
  hack/e2e-test.sh
  images/cluster/Dockerfile
  images/kwok/Dockerfile
  kustomize/kwok/kustomization.yaml
  kustomize/kwok/kwok-clusterrole.yaml
  kustomize/kwok/kwok-clusterrolebinding.yaml
  kustomize/kwok/kwok-deployment.yaml
  kustomize/kwok/kwok-serviceaccount.yaml
  test/controller/controller.test.sh
  test/kwok/fake-deployment.yaml
  test/kwok/fake-node.yaml
  test/kwok/kustomization.yaml
  test/kwok/kwok.test.sh
  test/kwokctl/kwokctl.test.sh
Labels: approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#6 Add Yibo to OWNERS
  OWNERS
Labels: approved, size/XS, cncf-cla: yes, lgtm

#20 Release on github with gh-action
  .github/workflows/releases.yaml
  Makefile
  hack/get-version.sh
  hack/releases.sh
  images/cluster/Dockerfile
  images/cluster/build.sh
  images/kwok/Dockerfile
  images/kwok/build.sh
  pkg/consts/consts.go
  pkg/kwokctl/vars/vars.go
  test/kwok/kwok.test.sh
  test/kwokctl/kwokctl.test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#21 Use scripts to maintain the supported_releases.txt file
   .github/workflows/bump_releases.yaml
  hack/supported_releases.sh
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L

#27 Modify the default working directory
  pkg/kwokctl/vars/vars.go
Labels: kind/feature, approved, size/S, cncf-cla: yes, lgtm

#34 Increase the waiting time for test creation nodes.
  test/kwokctl/kwokctl_benchmark_test.sh
Labels: approved, size/XS, cncf-cla: yes, lgtm, kind/flake

#33 Add verify
  Makefile
  hack/verify-all.sh
  hack/verify-boilerplate.go
  hack/verify-boilerplate.sh
  hack/verify-ends-newline.sh
  hack/verify-go-format.sh
  hack/verify-go-mod.sh
  pkg/consts/consts.go
  pkg/kwokctl/vars/vars.go
  test/kwok/fake-deployment.yaml
Labels: approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#35 Kwokctl uses the latest version of k8s
  Makefile
  hack/releases.sh
  pkg/consts/consts.go
  pkg/kwokctl/vars/vars.go
Labels: kind/feature, approved, size/S, cncf-cla: yes, lgtm
