Repository kubernetes-sigs/kwok, pull requests merged in 2022-12, with the labels that each got.

#112 Cleanup for gocritic
  .golangci.yaml
  pkg/kwok/controllers/controller.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/compose/compose.yaml.tpl
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#115 [CI] Jobs are no longer canceled after merge the main branch
  .github/workflows/test.yaml
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes

#113 Cleanup for gci
  .golangci.yaml
  cmd/kwokctl/main.go
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/kwokctl/k8s/kubeconfig.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/binary/prometheus.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/compose.go
  pkg/kwokctl/runtime/compose/prometheus.go
  pkg/kwokctl/runtime/kind/kind.go
  pkg/kwokctl/runtime/kind/kwok_controller_deployment.go
  pkg/kwokctl/runtime/kind/prometheus_deployment.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/M

#114 Cleanup for usestdlibvars
  .golangci.yaml
  pkg/kwokctl/utils/download.go
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#116 If kubectl exists no longer download
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/config.go
  pkg/kwokctl/vars/vars.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/M

#120 Bump k8s version
  go.mod
  go.sum
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#122 Optimize docker and kind output
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#94 Add docs for development
  docs/contributing/development.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/M

#128 Clean useless file
  test.yaml
Labels: size/XXL, approved, kind/cleanup, cncf-cla: yes

#127 Add new line check for .tpl file
  hack/verify-ends-newline.sh
  pkg/kwokctl/runtime/binary/prometheus.yaml.tpl
  pkg/kwokctl/runtime/kind/kind.yaml.tpl
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#129 Optimize the Ready wait strategy
  pkg/kwokctl/runtime/cluster.go
Labels: approved, kind/cleanup, size/S, cncf-cla: yes

#132 improve the help documents
  docs/contributing/development.md
  docs/examples/kwok-in-cluster.md
  docs/examples/kwok-in-local.md
  docs/examples/kwok-manage-nodes-and-pods.md
  docs/examples/kwokctl-manage-cluster.md
  docs/examples/kwokctl-snapshot.md
Labels: ok-to-test, approved, kind/documentation, cncf-cla: yes, lgtm, size/M

#141 delete PodScheduled condition
  pkg/kwok/controllers/templates/pod.status.tpl
Labels: kind/bug, approved, size/XS, cncf-cla: yes, lgtm

#142 check DeletionTimestamp when pod controller receives an add event
  pkg/kwok/controllers/pod_controller.go
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm

#143 Fix flake
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/utils.go
Labels: approved, cncf-cla: yes, kind/flake, size/L

#52 Support call cni plugin get pod ip
  .github/workflows/test.yaml
  go.mod
  go.sum
  kustomize/kwok-with-cni/kustomization.yaml
  kustomize/kwok-with-cni/kwok-deployment-patch.yaml
  kustomize/kwok/kwok-deployment.yaml
  pkg/cni/cni_linux.go
  pkg/cni/cni_other.go
  pkg/cni/netns_linux.go
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/pod_controller.go
  test/kwok-with-cni/fake-deployment.yaml
  test/kwok-with-cni/fake-node.yaml
  test/kwok-with-cni/kustomization.yaml
  test/kwok-with-cni/kwok-with-cni.test.sh
Labels: kind/feature, size/XL, approved, cncf-cla: yes

#145 fix staticcheck in golangci.yaml
  .golangci.yaml
  pkg/log/logger_ctl.go
Labels: ok-to-test, approved, kind/cleanup, size/S, cncf-cla: yes, lgtm

#146 Expand home dir before using kubeconfig for kwok
  pkg/kwok/cmd/root.go
  pkg/utils/path/path.go
Labels: kind/bug, ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#149 Fix api generate
  pkg/apis/doc.go
Labels: kind/bug, approved, size/XS, cncf-cla: yes

#151 Add periodic older version compatibility tests
  .github/workflows/cron-test.yaml
  hack/supported_releases.sh
  supported_releases.txt
  test/kwokctl/helper.sh
Labels: approved, cncf-cla: yes, size/M

#144 Download kind binary
  .github/workflows/test.yaml
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/v1alpha1/kwokctl_configuration_types.go
  pkg/config/vars.go
  pkg/consts/consts.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  test/kwokctl/kwokctl_kind_audit.test.sh
  test/kwokctl/kwokctl_kind_authorization.test.sh
  test/kwokctl/kwokctl_kind_snapshot.test.sh
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#155 Fix the error log output empty problem
  pkg/log/logger_ctl.go
  pkg/log/logger_ctl_test.go
Labels: kind/bug, ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#157 Fix failed to download kubectl
  pkg/config/vars.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#161 Add makefile command to simplify local development
  Makefile
  docs/contributing/development.md
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/M

#164 Fix compatibility
  pkg/config/compatibility/compatibility.go
  pkg/config/config.go
Labels: kind/bug, approved, size/S, cncf-cla: yes

#167 Print detail log if kubeconfig not found
  pkg/kwok/cmd/root.go
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#166 setKwokctlConfigurationDefaults function refactor
  pkg/config/vars.go
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#156 Add components for KwokctlConfiguration
  go.mod
  go.sum
  pkg/apis/internalversion/kwok_configuration_types.go
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/kwok_configuration_types.go
  pkg/apis/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/zz_generated.defaults.go
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/cmd/get/artifacts/artifacts.go
  pkg/kwokctl/components/consts.go
  pkg/kwokctl/components/doc.go
  pkg/kwokctl/components/etcd.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/components/kube_controller_manager.go
  pkg/kwokctl/components/kube_scheduler.go
  pkg/kwokctl/components/kwok_controller.go
  pkg/kwokctl/components/prometheus.go
  pkg/kwokctl/components/utils.go
  pkg/kwokctl/components/utils_test.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/binary/cluster_snapshot.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/cluster_snapshot.go
  pkg/kwokctl/runtime/compose/compose.go
  pkg/kwokctl/runtime/compose/compose.yaml.tpl
  pkg/kwokctl/runtime/config.go
  pkg/kwokctl/runtime/errors.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/cluster_snapshot.go
  pkg/kwokctl/runtime/registry.go
  pkg/utils/exec/cmd.go
  pkg/utils/file/file.go
  pkg/utils/slices/ref.go
  pkg/utils/slices/slices.go
  test/kwokctl/kwokctl_audit_test.sh
  test/kwokctl/kwokctl_authorization_test.sh
  test/kwokctl/kwokctl_benchmark_test.sh
  test/kwokctl/kwokctl_snapshot_test.sh
  test/kwokctl/kwokctl_workable_test.sh
Labels: kind/feature, size/XXL, approved, kind/cleanup, cncf-cla: yes

#173 Enable gocyclo in golangci
  .golangci.yaml
  pkg/kwokctl/k8s/doc.go
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#175 Fix flags
  pkg/kwokctl/cmd/create/cluster/cluster.go
Labels: kind/bug, approved, size/S, cncf-cla: yes

#176 Cleanup log
  pkg/log/logger_ctl.go
  pkg/utils/image/pull.go
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes

#178 Fix build website
  netlify.toml
  site/Makefile
Labels: kind/bug, approved, kind/documentation, cncf-cla: yes, size/M

#180 Fix the components configuration record error
  pkg/kwokctl/runtime/kind/cluster.go
Labels: kind/bug, approved, needs-ok-to-test, size/XS, cncf-cla: yes, lgtm

#179 fix: Cannot compile in bash 3.2
  Makefile
  hack/get-platform.sh
Labels: kind/bug, ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#183 Removes symbol when image prefix is not set
  Makefile
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#181 Update README.md
  README.md
Labels: approved, kind/documentation, cncf-cla: yes, size/M

#185 Support for loading configurations from multiple files
  cmd/kwok/main.go
  cmd/kwokctl/main.go
  pkg/config/config.go
  pkg/config/flags.go
Labels: kind/feature, approved, cncf-cla: yes, size/M

#184 cleanup development.md
  site/content/en/docs/contributing/development.md
Labels: approved, kind/documentation, size/XS, cncf-cla: yes

#186 fix: invalid reference format
  Makefile
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#188 Bump k8s version
  go.mod
  go.sum
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/M

#189 When a cluster component is disabled, the component image is not pulled
  pkg/kwokctl/runtime/compose/cluster.go
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm
