Repository kubernetes-sigs/kwok, pull requests merged in 2022-11, with the labels that each got.

#60 Fix cluster image
  images/cluster/Dockerfile
Labels: kind/bug, approved, size/XS, cncf-cla: yes, lgtm

#59 Move kwok/cmd to pkg
  cmd/kwok/main.go
  go.mod
  pkg/kwok/cmd/root.go
Labels: approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#61 Support for enabling kube authorization
  .github/workflows/test.yaml
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/pki/pki.go
  pkg/kwokctl/pki/pki_test.go
  pkg/kwokctl/pki/pkiutil.go
  pkg/kwokctl/pki/testdata/admin.crt
  pkg/kwokctl/pki/testdata/admin.key
  pkg/kwokctl/pki/testdata/ca.crt
  pkg/kwokctl/pki/testdata/openssl.cnf
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/compose.go
  pkg/kwokctl/runtime/compose/compose.yaml.tpl
  pkg/kwokctl/runtime/config.go
  pkg/kwokctl/vars/vars.go
  test/kwokctl/kwokctl_authorization_test.sh
  test/kwokctl/kwokctl_binary_authorization.test.sh
  test/kwokctl/kwokctl_docker_authorization.test.sh
  test/kwokctl/kwokctl_kind_authorization.test.sh
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm

#63 Cleanup: move controllers to pkg/kwok
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/kwok/controllers/templates/node.heartbeat.tpl
  pkg/kwok/controllers/templates/node.status.tpl
  pkg/kwok/controllers/templates/pod.status.tpl
  pkg/kwok/controllers/templates/templates.go
  pkg/kwok/controllers/utils.go
  pkg/kwok/controllers/utils_test.go
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#64 Cleanup: move locals inside
  pkg/kwok/cmd/root.go
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/M

#65 Parallel Up/Down cluster with binary runtime
  go.mod
  go.sum
  pkg/kwokctl/runtime/binary/cluster.go
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#71 node controller remove unused nodeAnnotationSelector field
  pkg/kwok/controllers/node_controller.go
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#69 make build support macos m1
  Makefile
  hack/get-platform.sh
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#70 subcommand silence usage and parent command print usage instead of print err
  pkg/kwok/cmd/root.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/cmd/create/create.go
  pkg/kwokctl/cmd/delete/cluster/cluster.go
  pkg/kwokctl/cmd/delete/delete.go
  pkg/kwokctl/cmd/get/artifacts/artifacts.go
  pkg/kwokctl/cmd/get/clusters/clusters.go
  pkg/kwokctl/cmd/get/get.go
  pkg/kwokctl/cmd/get/kubeconfig/kubeconfig.go
  pkg/kwokctl/cmd/kubectl/kubectl.go
  pkg/kwokctl/cmd/logs/logs.go
  pkg/kwokctl/cmd/root.go
  pkg/kwokctl/cmd/snapshot/restore/restore.go
  pkg/kwokctl/cmd/snapshot/save/save.go
  pkg/kwokctl/cmd/snapshot/snapshot.go
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#73 fix make build and image
  Makefile
Labels: kind/bug, ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#75 kwok & kwokctl support the --version flag
  pkg/kwok/cmd/root.go
  pkg/kwokctl/cmd/root.go
Labels: kind/feature, ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#77 fix staticcheck
  pkg/kwok/controllers/node_controller.go
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#76 add issue template
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/failing-test.yaml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#80 ignore files generated by editors
  .gitignore
Labels: ok-to-test, approved, kind/cleanup, size/S, cncf-cla: yes, lgtm

#82 Bump go version
  .github/workflows/releases.yaml
  .github/workflows/test.yaml
  go.mod
Labels: kind/feature, approved, size/XS, cncf-cla: yes, lgtm

#85 refactor template cache
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/renderer.go
  pkg/kwok/controllers/renderer_test.go
  pkg/kwok/controllers/utils.go
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#88 Ability to disable scheduler and controller-manager
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/compose.go
  pkg/kwokctl/runtime/compose/compose.yaml.tpl
  pkg/kwokctl/runtime/config.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/vars/vars.go
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#92 Fix flake
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwok/controllers/pod_controller_test.go
Labels: approved, cncf-cla: yes, size/M, kind/flake

#91 Bump etcd for kwokctl
  pkg/kwokctl/k8s/etcd.go
Labels: kind/feature, approved, size/S, cncf-cla: yes

#89 Fixed incorrect adding and trimming of prefix v
  pkg/kwokctl/vars/vars.go
Labels: kind/bug, approved, size/S, cncf-cla: yes

#81 Structured logging
  cmd/kwok/main.go
  cmd/kwokctl/main.go
  go.mod
  go.sum
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/kwok/controllers/utils_test.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/cmd/create/create.go
  pkg/kwokctl/cmd/delete/cluster/cluster.go
  pkg/kwokctl/cmd/delete/delete.go
  pkg/kwokctl/cmd/get/artifacts/artifacts.go
  pkg/kwokctl/cmd/get/clusters/clusters.go
  pkg/kwokctl/cmd/get/get.go
  pkg/kwokctl/cmd/get/kubeconfig/kubeconfig.go
  pkg/kwokctl/cmd/kubectl/kubectl.go
  pkg/kwokctl/cmd/logs/logs.go
  pkg/kwokctl/cmd/root.go
  pkg/kwokctl/cmd/snapshot/restore/restore.go
  pkg/kwokctl/cmd/snapshot/save/save.go
  pkg/kwokctl/cmd/snapshot/snapshot.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/binary/cluster_snapshot.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/cluster_snapshot.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/cluster_snapshot.go
  pkg/kwokctl/runtime/registry.go
  pkg/log/kobj.go
  pkg/log/logger.go
  pkg/log/logger_ctl.go
  pkg/log/logger_noop.go
  pkg/log/wrapper.go
  stages/pod-general.yaml
  test.yaml
Labels: kind/feature, size/XXL, approved, cncf-cla: yes

#96 Bump image for cloudbuild.yaml
  cloudbuild.yaml
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes

#95 Remove stages/pod-general.yaml
  stages/pod-general.yaml
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#99 Fix log wrapper
  pkg/log/wrapper.go
Labels: kind/bug, approved, size/S, cncf-cla: yes

#97 Add e2e for nerdctl
  .github/workflows/test.yaml
  Makefile
  hack/e2e-test.sh
  hack/requirements.sh
  test/kwokctl/helper.sh
  test/kwokctl/kwokctl_nerdctl.test.sh
  test/kwokctl/kwokctl_nerdctl_audit.test.sh
  test/kwokctl/kwokctl_nerdctl_authorization.test.sh
  test/kwokctl/kwokctl_nerdctl_benchmark.test.sh
  test/kwokctl/kwokctl_nerdctl_snapshot.test.sh
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#101 Fix log attrs for `with`
  pkg/log/logger_ctl.go
Labels: kind/bug, approved, cncf-cla: yes, size/M

#103 Fix get version
  pkg/kwokctl/k8s/etcd.go
  pkg/kwokctl/k8s/feature_gates.go
  pkg/kwokctl/vars/vars.go
Labels: approved, kind/cleanup, size/S, cncf-cla: yes

#104 Download `docker-compose` binary
  Makefile
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/config.go
  pkg/kwokctl/vars/vars.go
  test/kwokctl/kwokctl_docker_audit.test.sh
  test/kwokctl/kwokctl_docker_authorization.test.sh
  test/kwokctl/kwokctl_docker_snapshot.test.sh
Labels: kind/feature, approved, cncf-cla: yes, size/M

#106 Add golangci lint
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#109 Cleanup for errorlint
  .golangci.yaml
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwokctl/k8s/kubeconfig.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/binary/prometheus.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/prometheus.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/utils/untar.go
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/M

#111 Cleanup for gosimple and importas
  .golangci.yaml
  pkg/kwok/controllers/pod_controller.go
  pkg/kwokctl/utils/cmd_other.go
Labels: ok-to-test, approved, kind/cleanup, size/S, cncf-cla: yes, lgtm
