Repository kubernetes-sigs/kwok, pull requests merged in 2022-10, with the labels that each got.

#30 Add e2e for darwin and linux on gh-action
  .github/workflows/test.yaml
  test/kwokctl/helper.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#51 Set the default runtime to docker
  pkg/kwokctl/vars/vars.go
Labels: kind/feature, approved, size/XS, cncf-cla: yes, lgtm

#48 Update readme
  README.md
  docs/examples/kwok-in-cluster.md
  docs/examples/kwok-in-local.md
  docs/examples/kwok-manage-nodes-and-pods.md
  docs/examples/kwokctl-manage-cluster.md
  docs/examples/kwokctl-snapshot.md
  kustomize/kwok/kustomization.yaml
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/L

#53 add comment note for node-label-selector filter logic
  pkg/controllers/controller.go
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm
