Repository kubernetes-sigs/kwok, pull requests merged in 2023-03, with the labels that each got.

#337 Update docs
  README.md
  site/content/en/_index.md
  site/content/en/docs/contributing/getting-started.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/M

#338 Update the supported releases of cluster images
  Makefile
  cloudbuild.yaml
  test/release/build.test.sh
Labels: approved, kind/cleanup, cncf-cla: yes, lgtm, size/M

#341 [ci] Add rule to depguard for log
  .golangci.yaml
  pkg/log/logger.go
  pkg/log/logger_ctl.go
  pkg/log/logger_ctl_test.go
  pkg/log/logger_noop.go
  pkg/log/wrapper.go
Labels: approved, kind/cleanup, size/S, cncf-cla: yes

#339 Use a consistent term: kwok and kwokctl
  site/assets/_custom.scss
  site/content/en/_index.md
  site/content/en/docs/design/introduction.md
  site/content/en/docs/user/configuration.md
  site/content/en/docs/user/install.md
  site/content/en/docs/user/kwok-in-cluster.md
  site/content/en/docs/user/kwok-in-local.md
  site/content/en/docs/user/kwok-manage-nodes-and-pods.md
  site/content/en/docs/user/kwokctl-auditing.md
  site/content/en/docs/user/kwokctl-manage-cluster.md
  site/content/en/docs/user/kwokctl-snapshot.md
  site/content/en/docs/user/stages-configuration.md
  site/content/en/menu/index.md
  site/content/en/posts/the-website-is-available.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/L

#344 config: ignore empty documents while loading
  pkg/config/config.go
  pkg/config/config_test.go
Labels: kind/bug, ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#347 initialize nodeSelectorFunc when --manage-nodes-with-label-selector is set
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/controller_test.go
Labels: kind/bug, ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#345 Automated cherry pick of #344: config: ignore empty documents while loading
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, cncf-cla: yes, size/L

#349 [Docs] Refine text with minor changes
  site/content/en/docs/contributing/development.md
  site/content/en/docs/contributing/getting-started.md
  site/content/en/docs/design/introduction.md
  site/content/en/docs/user/configuration.md
  site/content/en/docs/user/kwok-manage-nodes-and-pods.md
  site/content/en/docs/user/stages-configuration.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/M

#336 [Docs] add get-started to userguide
  site/content/en/_index.md
  site/content/en/docs/user/getting-started.md
  site/content/en/docs/user/kwok-in-local.md
  site/content/en/menu/index.md
Labels: ok-to-test, approved, kind/documentation, cncf-cla: yes, lgtm, size/M

#325 [kwokctl] Support port exposure for etcd-port
  pkg/config/vars.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/components/etcd.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/kind.go
  pkg/kwokctl/runtime/kind/kind.yaml.tpl
  test/kwokctl/kwokctl_workable_test.sh
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#355 test: kwokctl test should build image depend on platform
  test/kwokctl/helper.sh
Labels: approved, size/XS, cncf-cla: yes, lgtm

#357 Clean up the entry of kwok controller
  pkg/kwok/cmd/root.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#358 Clean up the path utils
  pkg/config/config.go
  pkg/config/flags.go
  pkg/config/vars.go
  pkg/utils/path/path.go
  pkg/utils/path/path_other.go
  pkg/utils/path/path_test.go
  pkg/utils/path/path_windows.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#360 NewStagesFromYaml: decode check error
  pkg/kwok/controllers/lifecycle.go
Labels: kind/feature, ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#362 Automated cherry pick of #360: check error
  pkg/kwok/controllers/lifecycle.go
Labels: approved, size/XS, cncf-cla: yes, lgtm

#365 Respect PodCIDR of Node
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/pod_controller_test.go
  stages/pod-fast.yaml
  stages/pod-general.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/L

#366 Generic pools implementation
  pkg/kwok/controllers/renderer.go
  pkg/kwok/server/debugging_port_forword.go
  pkg/kwok/server/server.go
  pkg/utils/pools/doc.go
  pkg/utils/pools/pools.go
  pkg/utils/pools/pools_test.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#367 Fix hostNetwork
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/pod_controller_test.go
  stages/pod-fast.yaml
  stages/pod-general.yaml
Labels: kind/bug, approved, cncf-cla: yes, size/L

#376 [doc] Add architecture docs
  site/content/en/docs/design/architecture.md
  site/content/en/docs/design/introduction.md
  site/content/en/menu/index.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/M

#361 Acceleration Get IP
  pkg/kwok/controllers/node_controller.go
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#368 kwok-manage-nodes-and-pods.md: typo fix
  site/content/en/docs/user/kwok-manage-nodes-and-pods.md
Labels: ok-to-test, approved, kind/documentation, size/XS, cncf-cla: yes, lgtm

#377 Fix typo
  site/content/en/docs/design/architecture.md
Labels: approved, kind/documentation, size/XS, cncf-cla: yes

#369 [kwokctl] Support port exposure for kube-scheduler
  pkg/config/vars.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/components/kube_scheduler.go
  test/kwokctl/kwokctl_restart_test.sh
  test/kwokctl/kwokctl_workable_test.sh
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#372 Clean up kwok init
  pkg/kwok/cmd/root.go
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/M

#49 Generate document of command line
  go.mod
  go.sum
  hack/gen_cmd_docs/main.go
  hack/supported_releases.sh
  hack/update-all.sh
  hack/update-cmd-docs.sh
  hack/verify-all.sh
  hack/verify-cmd-docs.sh
  pkg/config/vars.go
  pkg/kwok/cmd/root.go
  pkg/kwok/cni/cni_linux.go
  pkg/kwok/cni/cni_other.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/cmd/create/create.go
  pkg/kwokctl/cmd/delete/cluster/cluster.go
  pkg/kwokctl/cmd/delete/delete.go
  pkg/kwokctl/cmd/etcdctl/etcdctl.go
  pkg/kwokctl/cmd/get/artifacts/artifacts.go
  pkg/kwokctl/cmd/get/clusters/clusters.go
  pkg/kwokctl/cmd/get/get.go
  pkg/kwokctl/cmd/get/kubeconfig/kubeconfig.go
  pkg/kwokctl/cmd/kubectl/kubectl.go
  pkg/kwokctl/cmd/logs/logs.go
  pkg/kwokctl/cmd/root.go
  pkg/kwokctl/cmd/snapshot/restore/restore.go
  pkg/kwokctl/cmd/snapshot/save/save.go
  pkg/kwokctl/cmd/snapshot/snapshot.go
  pkg/kwokctl/cmd/start/cluster/cluster.go
  pkg/kwokctl/cmd/start/start.go
  pkg/kwokctl/cmd/stop/cluster/cluster.go
  pkg/kwokctl/cmd/stop/stop.go
  site/content/en/docs/generated/kwok.md
  site/content/en/docs/generated/kwokctl.md
  site/content/en/docs/generated/kwokctl_create.md
  site/content/en/docs/generated/kwokctl_create_cluster.md
  site/content/en/docs/generated/kwokctl_delete.md
  site/content/en/docs/generated/kwokctl_delete_cluster.md
  site/content/en/docs/generated/kwokctl_etcdctl.md
  site/content/en/docs/generated/kwokctl_get.md
  site/content/en/docs/generated/kwokctl_get_artifacts.md
  site/content/en/docs/generated/kwokctl_get_clusters.md
  site/content/en/docs/generated/kwokctl_get_kubeconfig.md
  site/content/en/docs/generated/kwokctl_kubectl.md
  site/content/en/docs/generated/kwokctl_logs.md
  site/content/en/docs/generated/kwokctl_snapshot.md
  site/content/en/docs/generated/kwokctl_snapshot_restore.md
  site/content/en/docs/generated/kwokctl_snapshot_save.md
  site/content/en/docs/generated/kwokctl_start.md
  site/content/en/docs/generated/kwokctl_start_cluster.md
  site/content/en/docs/generated/kwokctl_stop.md
  site/content/en/docs/generated/kwokctl_stop_cluster.md
  site/content/en/menu/index.md
Labels: size/XL, approved, kind/documentation, cncf-cla: yes

#356 [Docs] Rewrite kwok-in-local.md
  site/content/en/docs/user/getting-started.md
  site/content/en/docs/user/kwok-in-local.md
  site/content/en/docs/user/kwok-out-cluster.md
  site/content/en/docs/user/kwokctl-manage-cluster.md
  site/content/en/menu/index.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/M

#383 [kwokctl] Support port exposure for kube-controller-manager
  pkg/config/vars.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/components/kube_controller_manager.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
  test/kwokctl/kwokctl_workable_test.sh
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#384 [doc] Add the next steps to the user documentation
  site/content/en/docs/user/all-in-one-image.md
  site/content/en/docs/user/getting-started.md
  site/content/en/docs/user/kwok-in-cluster.md
  site/content/en/docs/user/kwokctl-manage-cluster.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#385 fix some typos
  cloudbuild.yaml
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
Labels: approved, kind/cleanup, needs-ok-to-test, size/XS, cncf-cla: yes, lgtm

#387 [doc] Use goat for diagrams
  site/assets/mermaid.json
  site/assets/mermaid_dark.json
  site/content/en/docs/design/architecture.md
  site/content/en/docs/user/stages-configuration.md
  site/layouts/shortcodes/mermaid.html
  stages/pod-fast.yaml
  stages/pod-general.yaml
Labels: approved, kind/documentation, cncf-cla: yes, size/L

#388 [kwokctl] Change to detect runtime only on Linux
  pkg/config/vars.go
Labels: kind/feature, approved, kind/cleanup, size/S, cncf-cla: yes

#394 Add scripts for yamllint
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .golangci.yaml
  .yamllint.conf
  hack/verify-all.sh
  hack/verify-yamllint.sh
  test/lifecycle/fake-pod-stages.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M

#400 Fixes node not initialized
  stages/node-fast.yaml
Labels: kind/bug, approved, size/XS, cncf-cla: yes

#405 Fix diagram format
  site/content/en/docs/design/architecture.md
Labels: approved, kind/documentation, cncf-cla: yes, size/M

#386 [kubectl] set/remove current-context after cluster create/deletion
  pkg/kwok/cmd/root.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/cmd/delete/cluster/cluster.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/binary/cluster_context.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/cluster_context.go
  pkg/kwokctl/runtime/config.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/cluster_context.go
  pkg/utils/kubeconfig/doc.go
  pkg/utils/kubeconfig/kubeconfig.go
  pkg/utils/kubeconfig/kubeconfig_test.go
  site/content/en/docs/generated/kwok.md
  site/content/en/docs/generated/kwokctl_create_cluster.md
  site/content/en/docs/generated/kwokctl_delete_cluster.md
  test/kwokctl/kwokctl_workable_test.sh
Labels: kind/feature, size/XL, approved, cncf-cla: yes

#403 [kwokctl] Supports configuration of node heartbeat interval
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/v1alpha1/zz_generated.defaults.go
  pkg/kwokctl/components/kube_controller_manager.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
Labels: kind/feature, approved, cncf-cla: yes, size/L

#396 Fix some conditions not updating
  pkg/kwok/controllers/node_controller.go
  pkg/utils/expression/selector.go
  stages/node-fast.yaml
Labels: kind/bug, kind/feature, approved, cncf-cla: yes, size/L

#409 Fix node controller accidental exit
  pkg/kwok/controllers/node_controller.go
Labels: kind/bug, approved, size/XS, cncf-cla: yes

#311 support extra args
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/kwokctl/components/etcd.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/components/kube_controller_manager.go
  pkg/kwokctl/components/kube_scheduler.go
  pkg/kwokctl/components/kwok_controller.go
  pkg/kwokctl/components/prometheus.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/kind.go
  pkg/kwokctl/runtime/kind/kind.yaml.tpl
  pkg/kwokctl/runtime/kind/kwok_controller_pod.go
  pkg/kwokctl/runtime/kind/kwok_controller_pod.yaml.tpl
  pkg/kwokctl/runtime/kind/prometheus_deployment.go
  pkg/kwokctl/runtime/kind/prometheus_deployment.yaml.tpl
  pkg/kwokctl/runtime/util.go
  test/kwokctl/fake-kwok-config-le-1-17.yaml
  test/kwokctl/fake-kwok-config.yaml
  test/kwokctl/kwokctl_workable_test.sh
Labels: kind/feature, ok-to-test, approved, kind/api-change, cncf-cla: yes, lgtm, size/L

#414 Clean up the Stage
  pkg/kwok/controllers/controller_test.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/pod_controller_test.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#420 Cancel job when resource is deleted
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/pod_controller.go
Labels: kind/bug, approved, size/S, cncf-cla: yes

#419 Support for getting versions from tags
  pkg/utils/version/version.go
Labels: kind/feature, approved, size/S, cncf-cla: yes

#412 [kwokctl] Add check for snapshot file existence
  pkg/kwokctl/cmd/snapshot/restore/restore.go
  pkg/kwokctl/cmd/snapshot/save/save.go
Labels: kind/bug, approved, size/XS, cncf-cla: yes

#425 Clean up hack
  hack/boilerplate/boilerplate.go.txt
  hack/tools/tools.go
  hack/update-codegen.sh
  hack/verify-boilerplate.sh
  hack/verify_boilerplate/main.go
Labels: approved, kind/cleanup, size/S, cncf-cla: yes

#426 Fix flake test
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/utils/wait/doc.go
  pkg/utils/wait/wait.go
Labels: approved, cncf-cla: yes, kind/flake, size/L

#428 Fix list style of site blog
  site/assets/plugins/_numbered.scss
Labels: approved, kind/documentation, size/XS, cncf-cla: yes

#432 [doc] Update blogs
  site/config.yaml
  site/content/en/posts/2022-12-12-the-website-is-available.md
  site/content/en/posts/2023-03-01-introducing-kwok.md
  site/layouts/posts/list.html
  site/layouts/posts/single.html
Labels: approved, kind/documentation, cncf-cla: yes, size/L

#433 add unit test for selector
  pkg/utils/expression/selector_test.go
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#431 [doc] Update the manage nodes and pods
  site/content/en/docs/user/kwok-manage-nodes-and-pods.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#435 [doc] Update links
  site/Makefile
  site/content/en/_index.md
  site/content/en/docs/user/kwokctl-auditing.md
  site/content/en/docs/user/stages-configuration.md
  site/content/en/posts/2023-03-01-introducing-kwok.md
  site/static/img/demo/audit-log.svg
  site/static/img/demo/manage-clusters.svg
  site/static/img/demo/stages-pod-fast.svg
  site/static/img/demo/stages-pod-general.svg
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#430 [kwok] Provided service for exec
  .github/workflows/test.yaml
  go.mod
  go.sum
  pkg/apis/internalversion/cluster_exec_types.go
  pkg/apis/internalversion/conversion.go
  pkg/apis/internalversion/exec_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/cluster_exec_types.go
  pkg/apis/v1alpha1/exec_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/config/config.go
  pkg/kwok/cmd/root.go
  pkg/kwok/server/debugging_exec.go
  pkg/kwok/server/debugging_exec_other.go
  pkg/kwok/server/debugging_exec_windows.go
  pkg/kwok/server/remotecommand/exec.go
  pkg/kwok/server/server.go
  test/kwokctl/exec.yaml
  test/kwokctl/kwokctl_binary_exec.test.sh
  test/kwokctl/kwokctl_docker_exec.test.sh
  test/kwokctl/kwokctl_exec_test.sh
  test/kwokctl/kwokctl_kind_exec.test.sh
  test/kwokctl/kwokctl_nerdctl_exec.test.sh
Labels: size/XXL, approved, cncf-cla: yes

#381 [kwokctl] Support k8s format for snapshot
  go.mod
  pkg/kwokctl/cmd/snapshot/restore/restore.go
  pkg/kwokctl/cmd/snapshot/save/save.go
  pkg/kwokctl/runtime/binary/cluster_snapshot.go
  pkg/kwokctl/runtime/cluster_snapshot.go
  pkg/kwokctl/runtime/compose/cluster_snapshot.go
  pkg/kwokctl/runtime/config.go
  pkg/kwokctl/runtime/kind/cluster_snapshot.go
  pkg/kwokctl/snapshot/doc.go
  pkg/kwokctl/snapshot/load.go
  pkg/kwokctl/snapshot/load_test.go
  pkg/kwokctl/snapshot/runtime.go
  pkg/kwokctl/snapshot/save.go
  site/content/en/docs/generated/kwokctl_snapshot_restore.md
  site/content/en/docs/generated/kwokctl_snapshot_save.md
  site/content/en/docs/user/kwokctl-snapshot.md
  test/kwokctl/kwokctl_snapshot_test.sh
Labels: kind/feature, size/XL, approved, cncf-cla: yes

#427 Support parse string for flag -v
  pkg/log/flags.go
  pkg/log/wrapper.go
  pkg/log/wrapper_test.go
  site/content/en/docs/generated/kwok.md
  site/content/en/docs/generated/kwokctl.md
  site/content/en/docs/generated/kwokctl_create.md
  site/content/en/docs/generated/kwokctl_create_cluster.md
  site/content/en/docs/generated/kwokctl_delete.md
  site/content/en/docs/generated/kwokctl_delete_cluster.md
  site/content/en/docs/generated/kwokctl_etcdctl.md
  site/content/en/docs/generated/kwokctl_get.md
  site/content/en/docs/generated/kwokctl_get_artifacts.md
  site/content/en/docs/generated/kwokctl_get_clusters.md
  site/content/en/docs/generated/kwokctl_get_kubeconfig.md
  site/content/en/docs/generated/kwokctl_kubectl.md
  site/content/en/docs/generated/kwokctl_logs.md
  site/content/en/docs/generated/kwokctl_snapshot.md
  site/content/en/docs/generated/kwokctl_snapshot_restore.md
  site/content/en/docs/generated/kwokctl_snapshot_save.md
  site/content/en/docs/generated/kwokctl_start.md
  site/content/en/docs/generated/kwokctl_start_cluster.md
  site/content/en/docs/generated/kwokctl_stop.md
  site/content/en/docs/generated/kwokctl_stop_cluster.md
Labels: kind/feature, approved, cncf-cla: yes, size/L

#440 Fix featureGates and runtimeConfig on kind runtime
  pkg/kwokctl/runtime/kind/kind.yaml.tpl
Labels: kind/bug, approved, size/XS, cncf-cla: yes

#443 Fix flake
  test/kwokctl/kwokctl_snapshot_test.sh
Labels: approved, kind/failing-test, size/XS, cncf-cla: yes

#442 Clean up port forward
  pkg/kwok/server/debugging_port_forword.go
Labels: approved, kind/cleanup, size/S, cncf-cla: yes
