Repository kubernetes-sigs/kwok, pull requests merged in 2023-08, with the labels that each got.

#750 [doc] Fix broken link and update support matrix
  site/content/en/_index.md
  site/content/en/docs/user/stages-configuration.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, release-note-none

#749 Tidy up this embedded CRs
  kustomize/stage/node/fast/embed.go
  kustomize/stage/node/heartbeat/embed.go
  kustomize/stage/pod/fast/embed.go
  pkg/config/config.go
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/controller_test.go
  pkg/kwok/controllers/lifecycle.go
  pkg/kwok/controllers/lifecycle_test.go
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/kwokctl/cmd/scale/scale.go
  pkg/kwokctl/runtime/cluster.go
  pkg/utils/slices/slices.go
  stages/README.md
Labels: approved, kind/cleanup, cncf-cla: yes, release-note-none, size/L

#751 pkg/kwok/controllers: should not add duplicate job
  kustomize/rbac/role.yaml
  pkg/apis/v1alpha1/doc.go
  pkg/kwok/controllers/node_controller.go
Labels: kind/bug, ok-to-test, tide/merge-method-squash, approved, size/S, kind/api-change, cncf-cla: yes, lgtm, release-note-none

#754 Fix job not being available for some leases
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/node_lease_controller.go
  pkg/kwok/controllers/pod_controller.go
  pkg/utils/maps/sync.go
Labels: kind/bug, approved, cncf-cla: yes, size/M, release-note-none

#757 Makefile: cleanup unused vendor code
  Makefile
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm, release-note-none

#753 Support for multi-controller work on host network
  kustomize/kwok-with-cni/deployment-patch.yaml
  kustomize/kwok-with-cni/kustomization.yaml
  kustomize/kwok/deployment.yaml
  pkg/kwok/cmd/root.go
  pkg/utils/client/clientset.go
  test/kwok/kustomization.yaml
Labels: kind/feature, approved, kind/cleanup, cncf-cla: yes, release-note-none, size/L

#760 Fix flake test
  test/kwokctl/kwokctl_benchmark_test.sh
  test/kwokctl/kwokctl_exec_test.sh
  test/kwokctl/kwokctl_snapshot_test.sh
Labels: approved, size/S, cncf-cla: yes, kind/flake, release-note-none

#603 [kwokctl] Integrate jaeger
  .golangci.yaml
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/config/vars.go
  pkg/consts/consts.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/components/jaeger.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/k8s/kube_apiserver_tracing_config.go
  pkg/kwokctl/k8s/kube_apiserver_tracing_config.yaml.tpl
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/jaeger_deployment.go
  pkg/kwokctl/runtime/kind/jaeger_deployment.yaml.tpl
  pkg/kwokctl/runtime/kind/kind.go
  pkg/kwokctl/runtime/kind/kind.yaml.tpl
  pkg/utils/exec/version.go
  pkg/utils/version/version.go
  pkg/utils/version/version_test.go
  site/content/en/docs/generated/apis.md
  site/content/en/docs/generated/kwokctl_create_cluster.md
  test/kwokctl/kwokctl_with_dryrun.test.sh
  test/kwokctl/kwokctl_workable_test.sh
  test/kwokctl/testdata/binary/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/docker/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/podman/create_cluster_with_verbosity.txt
Labels: kind/feature, ok-to-test, size/XL, approved, kind/documentation, kind/api-change, cncf-cla: yes, release-note, lgtm

#761 Fix dryrun on jaeger
  pkg/kwokctl/runtime/binary/cluster.go
  test/kwokctl/testdata/binary/create_cluster_with_verbosity.txt
Labels: kind/bug, approved, size/XS, cncf-cla: yes, release-note-none

#755 [kwokctl] Integrate dashboard
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/config/vars.go
  pkg/consts/consts.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/components/dashboard.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/dashboard_deployment.go
  pkg/kwokctl/runtime/kind/dashboard_deployment.yaml.tpl
  pkg/kwokctl/runtime/kind/kind.go
  pkg/kwokctl/runtime/kind/kind.yaml.tpl
  site/content/en/docs/generated/apis.md
  site/content/en/docs/generated/kwokctl_create_cluster.md
  test/kwokctl/kwokctl_with_dryrun.test.sh
  test/kwokctl/kwokctl_workable_test.sh
  test/kwokctl/testdata/docker/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/podman/create_cluster_with_verbosity.txt
Labels: kind/feature, size/XL, approved, kind/documentation, kind/api-change, cncf-cla: yes, release-note

#763 Fix flake load resource
  pkg/kwokctl/snapshot/load.go
Labels: approved, size/S, cncf-cla: yes, kind/flake, release-note-none

#758 Refactor the events
  go.mod
  go.sum
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwok/controllers/node_lease_controller.go
  pkg/kwok/controllers/node_lease_controller_test.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/kwok/controllers/utils.go
  pkg/kwok/metrics/metrics.go
  pkg/kwok/server/metrics.go
  pkg/kwok/server/service_discovery.go
  pkg/utils/informer/doc.go
  pkg/utils/informer/event.go
  pkg/utils/informer/informer.go
  pkg/utils/maps/sync.go
  pkg/utils/queue/delaying_queue.go
  pkg/utils/queue/doc.go
  pkg/utils/queue/queue.go
  test/kwokctl/kwokctl_benchmark_test.sh
  test/kwokctl/suite.sh
Labels: size/XXL, approved, kind/cleanup, kind/api-change, cncf-cla: yes, release-note

#766 Fix flake load resource
  pkg/kwok/server/debugging_port_forword.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/snapshot/load.go
  pkg/utils/client/lazyrestmapper.go
  test/kwokctl/kwokctl_port_forward_test.sh
Labels: approved, cncf-cla: yes, size/M, kind/flake, release-note-none

#764 Clean up same code
  pkg/kwokctl/k8s/kube_apiserver_tracing_config.go
  pkg/kwokctl/runtime/binary/prometheus.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/prometheus.go
  pkg/kwokctl/runtime/kind/jaeger_deployment.go
  pkg/kwokctl/runtime/kind/jaeger_deployment.yaml.tpl
  pkg/kwokctl/runtime/kind/kind.go
  pkg/kwokctl/runtime/kind/kind.yaml.tpl
  pkg/kwokctl/runtime/kind/kwok_controller_pod.go
  pkg/kwokctl/runtime/kind/kwok_controller_pod.yaml.tpl
  pkg/kwokctl/runtime/kind/prometheus_deployment.go
  pkg/kwokctl/runtime/kind/prometheus_deployment.yaml.tpl
  test/kwokctl/testdata/kind-podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind/create_cluster_with_verbosity.txt
Labels: size/XXL, approved, kind/cleanup, cncf-cla: yes, release-note-none

#770 Bump nerdctl
  .github/workflows/test.yaml
Labels: approved, kind/cleanup, size/S, cncf-cla: yes, release-note-none

#772 Bump k8s to 1.28
  .github/workflows/test.yaml
  cloudbuild.yaml
  go.mod
  go.sum
  hack/requirements.sh
  hack/tools/tools.go
  kustomize/crd/bases/kwok.x-k8s.io_attaches.yaml
  kustomize/crd/bases/kwok.x-k8s.io_clusterattaches.yaml
  kustomize/crd/bases/kwok.x-k8s.io_clusterexecs.yaml
  kustomize/crd/bases/kwok.x-k8s.io_clusterlogs.yaml
  kustomize/crd/bases/kwok.x-k8s.io_clusterportforwards.yaml
  kustomize/crd/bases/kwok.x-k8s.io_execs.yaml
  kustomize/crd/bases/kwok.x-k8s.io_logs.yaml
  kustomize/crd/bases/kwok.x-k8s.io_metrics.yaml
  kustomize/crd/bases/kwok.x-k8s.io_portforwards.yaml
  kustomize/crd/bases/kwok.x-k8s.io_stages.yaml
  pkg/consts/consts.go
  pkg/kwok/server/debugging_attach.go
  pkg/kwok/server/debugging_exec.go
  pkg/kwok/server/debugging_port_forword.go
  pkg/kwok/server/portforward/constants.go
  pkg/kwok/server/portforward/httpstream.go
  pkg/kwok/server/portforward/httpstream_test.go
  pkg/kwok/server/portforward/portforward.go
  pkg/kwok/server/portforward/websocket.go
  pkg/kwok/server/portforward/websocket_test.go
  pkg/kwok/server/remotecommand/attach.go
  pkg/kwok/server/remotecommand/constants.go
  pkg/kwok/server/remotecommand/doc.go
  pkg/kwok/server/remotecommand/exec.go
  pkg/kwok/server/remotecommand/httpstream.go
  pkg/kwok/server/remotecommand/websocket.go
  pkg/kwokctl/k8s/feature_gates_data.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
  site/content/en/docs/user/kwokctl-platform-specific-binaries.md
  supported_releases.txt
  test/kwokctl/testdata/binary/create_cluster.txt
  test/kwokctl/testdata/binary/create_cluster_with_extra.txt
  test/kwokctl/testdata/binary/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/docker/create_cluster.txt
  test/kwokctl/testdata/docker/create_cluster_with_extra.txt
  test/kwokctl/testdata/docker/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind-podman/create_cluster.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind/create_cluster.txt
  test/kwokctl/testdata/kind/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/nerdctl/create_cluster.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_extra.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/podman/create_cluster.txt
  test/kwokctl/testdata/podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/podman/create_cluster_with_verbosity.txt
Labels: kind/feature, size/XXL, approved, kind/documentation, cncf-cla: yes, release-note-none

#773 Fix build in ci
  cloudbuild.yaml
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes, release-note-none

#779 Fix decode yaml
  pkg/utils/yaml/decoder.go
Labels: kind/bug, approved, size/XS, cncf-cla: yes, release-note-none

#781 Workaround for qemu on MacOS in CI
  .github/workflows/test.yaml
Labels: approved, size/XS, cncf-cla: yes, kind/flake, release-note-none

#783 Fix kustomize in Ci
  Makefile
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes, release-note-none

#782 Bump controller tools
  go.mod
  go.sum
  kustomize/crd/bases/kwok.x-k8s.io_attaches.yaml
  kustomize/crd/bases/kwok.x-k8s.io_clusterattaches.yaml
  kustomize/crd/bases/kwok.x-k8s.io_clusterexecs.yaml
  kustomize/crd/bases/kwok.x-k8s.io_clusterlogs.yaml
  kustomize/crd/bases/kwok.x-k8s.io_clusterportforwards.yaml
  kustomize/crd/bases/kwok.x-k8s.io_execs.yaml
  kustomize/crd/bases/kwok.x-k8s.io_logs.yaml
  kustomize/crd/bases/kwok.x-k8s.io_metrics.yaml
  kustomize/crd/bases/kwok.x-k8s.io_portforwards.yaml
  kustomize/crd/bases/kwok.x-k8s.io_stages.yaml
Labels: approved, kind/cleanup, cncf-cla: yes, size/M, release-note-none

#780 Clean up some code
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
  pkg/consts/consts.go
  pkg/kwok/server/debugging_exec.go
  pkg/kwokctl/components/dashboard.go
  pkg/kwokctl/components/etcd.go
  pkg/kwokctl/components/jaeger.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/components/kube_controller_manager.go
  pkg/kwokctl/components/kube_scheduler.go
  pkg/kwokctl/components/kwok_controller.go
  pkg/kwokctl/components/prometheus.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/binary/cluster_snapshot.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/cluster_snapshot.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/cluster_snapshot.go
  pkg/kwokctl/snapshot/load.go
  pkg/kwokctl/snapshot/runtime.go
  pkg/kwokctl/snapshot/save.go
  pkg/utils/client/util.go
Labels: size/XXL, approved, kind/cleanup, cncf-cla: yes, release-note-none

#785 [kwokctl] Add --enable-crds
  kustomize/kwok/deployment.yaml
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/internalversion/kwok_configuration_types.go
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/kwok/cmd/root.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/components/kwok_controller.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/kwok_controller_pod.go
  pkg/kwokctl/runtime/kind/kwok_controller_pod.yaml.tpl
  site/content/en/docs/generated/apis.md
  site/content/en/docs/generated/kwok.md
  site/content/en/docs/generated/kwokctl_create_cluster.md
  test/kwokctl/kwokctl_exec_test.sh
  test/kwokctl/kwokctl_port_forward_test.sh
Labels: approved, kind/documentation, kind/api-change, cncf-cla: yes, release-note, size/L

#788 Turn to alpha
  pkg/consts/consts.go
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes, release-note-none

#771 Update docs for 0.4
  site/content/en/docs/user/all-in-one-image.md
  site/content/en/docs/user/kwok-in-cluster-old.md
  site/content/en/docs/user/kwok-in-cluster.md
  site/content/en/docs/user/kwok-manage-nodes-and-pods.md
  site/content/en/docs/user/kwok-out-cluster.md
Labels: approved, kind/documentation, cncf-cla: yes, release-note-none, size/L

#789 Fix path registration causing overwrites
  pkg/kwok/server/metrics.go
  pkg/kwok/server/server.go
Labels: kind/bug, approved, cncf-cla: yes, release-note, size/M
