Repository kubernetes-sigs/kwok, pull requests merged in 2023-07, with the labels that each got.

#698 Support release manifests
  .github/workflows/releases.yaml
  .gitignore
  Makefile
  cloudbuild.yaml
  hack/manifests.sh
  test/release/build.test.sh
Labels: kind/feature, approved, cncf-cla: yes, size/L

#699 Refactor exec
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/binary/cluster_snapshot.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/exec.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/utils/exec/cmd.go
  pkg/utils/exec/exec.go
  test/kwokctl/suite.sh
  test/kwokctl/testdata/binary/create_cluster.txt
  test/kwokctl/testdata/binary/create_cluster_with_extra.txt
  test/kwokctl/testdata/binary/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/binary/snapshot_restore_etcd.txt
  test/kwokctl/testdata/binary/start_cluster.txt
  test/kwokctl/testdata/binary/stop_cluster.txt
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#701 Fix build kwok.yaml in cloudbuild
  cloudbuild.yaml
  hack/requirements.sh
Labels: kind/bug, approved, size/S, cncf-cla: yes

#691 add extra envs in KwokctlConfiguration
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/kwokctl/components/etcd.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/components/kube_controller_manager.go
  pkg/kwokctl/components/kube_scheduler.go
  pkg/kwokctl/components/kwok_controller.go
  pkg/kwokctl/components/prometheus.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/kind.go
  pkg/kwokctl/runtime/kind/kwok_controller_pod.go
  pkg/kwokctl/runtime/kind/kwok_controller_pod.yaml.tpl
  pkg/kwokctl/runtime/kind/prometheus_deployment.go
  pkg/kwokctl/runtime/kind/prometheus_deployment.yaml.tpl
  site/content/en/docs/generated/apis.md
  test/kwokctl/testdata/binary/create_cluster_with_extra.txt
  test/kwokctl/testdata/docker/create_cluster_with_extra.txt
  test/kwokctl/testdata/extra.yaml
  test/kwokctl/testdata/kind-podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind/create_cluster_with_extra.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_extra.txt
  test/kwokctl/testdata/podman/create_cluster_with_extra.txt
Labels: kind/feature, approved, kind/documentation, kind/api-change, cncf-cla: yes, lgtm, size/L

#702 Fix prefix of bucket
  Makefile
  hack/manifests.sh
  test/release/build.test.sh
Labels: kind/bug, approved, size/S, cncf-cla: yes

#703 Adjusting the config and CRD checks
  kustomize/kwok-with-cni/deployment-patch.yaml
  kustomize/kwok/deployment.yaml
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/controller.go
  pkg/kwokctl/runtime/cluster.go
Labels: kind/feature, approved, cncf-cla: yes, size/L

#646 [kwokctl] Fix binary runtime on windows
  .github/workflows/test.yaml
  pkg/config/config.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/exec.go
  pkg/utils/path/path.go
  pkg/utils/version/version_test.go
  test/kwokctl/helper.sh
  test/kwokctl/kwokctl_workable_test.sh
  test/kwokctl/suite.sh
Labels: kind/feature, approved, cncf-cla: yes, size/L

#677 Specify the user and group to be executed for kwokctl exec
  kustomize/crd/bases/kwok.x-k8s.io_clusterexecs.yaml
  kustomize/crd/bases/kwok.x-k8s.io_execs.yaml
  pkg/apis/internalversion/exec_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/exec_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/kwok/server/debugging_exec.go
  pkg/utils/exec/cmd_other.go
  pkg/utils/exec/cmd_windows.go
  pkg/utils/exec/exec.go
  site/content/en/docs/generated/apis.md
  test/kwokctl/exec-security-context.yaml
  test/kwokctl/kwokctl_exec_test.sh
  test/kwokctl/suite.sh
Labels: kind/feature, approved, kind/documentation, kind/api-change, cncf-cla: yes, lgtm, size/L

#708 Move the installed to local bin directory
  .github/workflows/test.yaml
  .gitignore
  Makefile
  cloudbuild.yaml
  hack/requirements.sh
  test/kwok-with-cni/kwok-with-cni.test.sh
  test/kwok/kwok.test.sh
  test/kwokctl/helper.sh
  test/kwokctl/kwokctl_with_dryrun.test.sh
  test/kwokctl/suite.sh
  test/kwokctl/testdata/binary/create_cluster.txt
  test/kwokctl/testdata/binary/create_cluster_with_extra.txt
  test/kwokctl/testdata/binary/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/binary/export_logs.txt
  test/kwokctl/testdata/binary/snapshot_restore_etcd.txt
  test/kwokctl/testdata/binary/snapshot_save_etcd.txt
  test/kwokctl/testdata/binary/start_cluster.txt
  test/kwokctl/testdata/binary/stop_cluster.txt
  test/kwokctl/testdata/docker/create_cluster.txt
  test/kwokctl/testdata/docker/create_cluster_with_extra.txt
  test/kwokctl/testdata/docker/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/docker/export_logs.txt
  test/kwokctl/testdata/docker/snapshot_restore_etcd.txt
  test/kwokctl/testdata/kind-podman/create_cluster.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind-podman/export_logs.txt
  test/kwokctl/testdata/kind-podman/snapshot_restore_etcd.txt
  test/kwokctl/testdata/kind-podman/snapshot_save_etcd.txt
  test/kwokctl/testdata/kind/create_cluster.txt
  test/kwokctl/testdata/kind/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind/export_logs.txt
  test/kwokctl/testdata/kind/snapshot_restore_etcd.txt
  test/kwokctl/testdata/kind/snapshot_save_etcd.txt
  test/kwokctl/testdata/nerdctl/create_cluster.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_extra.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/nerdctl/export_logs.txt
  test/kwokctl/testdata/nerdctl/snapshot_restore_etcd.txt
  test/kwokctl/testdata/podman/create_cluster.txt
  test/kwokctl/testdata/podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/podman/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/podman/export_logs.txt
  test/kwokctl/testdata/podman/snapshot_restore_etcd.txt
Labels: size/XL, approved, kind/cleanup, cncf-cla: yes

#706 📖 update install doc (go install)
  site/content/en/docs/user/installation.md
Labels: approved, kind/documentation, size/XS, cncf-cla: yes, lgtm

#710 Fix snapshot
  pkg/kwokctl/snapshot/load.go
  pkg/kwokctl/snapshot/runtime.go
  pkg/kwokctl/snapshot/save.go
Labels: kind/bug, approved, cncf-cla: yes, size/M

#711 Support comma-separated on --enable-crd and --config
  pkg/config/flags.go
  pkg/kwok/cmd/root.go
  site/content/en/docs/generated/kwok.md
  site/content/en/docs/generated/kwokctl.md
  site/content/en/docs/generated/kwokctl_config.md
  site/content/en/docs/generated/kwokctl_config_reset.md
  site/content/en/docs/generated/kwokctl_config_tidy.md
  site/content/en/docs/generated/kwokctl_config_view.md
  site/content/en/docs/generated/kwokctl_create.md
  site/content/en/docs/generated/kwokctl_create_cluster.md
  site/content/en/docs/generated/kwokctl_delete.md
  site/content/en/docs/generated/kwokctl_delete_cluster.md
  site/content/en/docs/generated/kwokctl_etcdctl.md
  site/content/en/docs/generated/kwokctl_export.md
  site/content/en/docs/generated/kwokctl_export_logs.md
  site/content/en/docs/generated/kwokctl_get.md
  site/content/en/docs/generated/kwokctl_get_artifacts.md
  site/content/en/docs/generated/kwokctl_get_clusters.md
  site/content/en/docs/generated/kwokctl_get_kubeconfig.md
  site/content/en/docs/generated/kwokctl_kubectl.md
  site/content/en/docs/generated/kwokctl_logs.md
  site/content/en/docs/generated/kwokctl_snapshot.md
  site/content/en/docs/generated/kwokctl_snapshot_export.md
  site/content/en/docs/generated/kwokctl_snapshot_restore.md
  site/content/en/docs/generated/kwokctl_snapshot_save.md
  site/content/en/docs/generated/kwokctl_start.md
  site/content/en/docs/generated/kwokctl_start_cluster.md
  site/content/en/docs/generated/kwokctl_stop.md
  site/content/en/docs/generated/kwokctl_stop_cluster.md
Labels: kind/feature, approved, kind/documentation, cncf-cla: yes, size/L

#715 Optimise, pre-compile jq code
  pkg/utils/expression/query.go
Labels: approved, kind/cleanup, size/S, cncf-cla: yes

#721 Add create node lease retry
  pkg/kwok/controllers/node_lease_controller.go
Labels: kind/bug, approved, size/S, cncf-cla: yes, release-note-none

#718 Clean up snapshot
  pkg/kwokctl/cmd/snapshot/export/export.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/cluster_snapshot.go
  pkg/kwokctl/snapshot/load.go
  pkg/kwokctl/snapshot/save.go
Labels: approved, kind/cleanup, cncf-cla: yes, release-note-none, size/L

#720 Fix unwanted loop
  pkg/kwok/controllers/utils.go
Labels: kind/bug, approved, size/XS, cncf-cla: yes, release-note-none

#669 Support for indicators of different dimensions
  go.mod
  go.sum
  kustomize/crd/bases/kwok.x-k8s.io_metrics.yaml
  pkg/apis/internalversion/conversion.go
  pkg/apis/internalversion/metric_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/v1alpha1/metric_types.go
  pkg/apis/v1alpha1/zz_generated.defaults.go
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/kwok/metrics/cel/evaluate.go
  pkg/kwok/metrics/cel/evaluate_test.go
  pkg/kwok/metrics/cel/funcs.go
  pkg/kwok/metrics/counter.go
  pkg/kwok/metrics/gauge.go
  pkg/kwok/metrics/histogram.go
  pkg/kwok/metrics/metrics.go
  pkg/kwok/server/metrics.go
  pkg/utils/maps/sync.go
  site/content/en/docs/generated/apis.md
  test/kwokctl/kwokctl_metric_test.sh
  test/kwokctl/metric.yaml
Labels: kind/feature, size/XXL, approved, kind/documentation, kind/api-change, cncf-cla: yes, release-note

#707 [kwokctl] Add scale subcommand
  .github/workflows/test.yaml
  kustomize/kwokctl/kustomization.yaml
  kustomize/kwokctl/resource/embed.go
  kustomize/kwokctl/resource/kustomization.yaml
  kustomize/kwokctl/resource/node.yaml
  kustomize/kwokctl/resource/pod.yaml
  pkg/apis/config/v1alpha1/kwokctl_resource_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/internalversion/conversion.go
  pkg/apis/internalversion/kwokctl_resource_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/config/config.go
  pkg/kwok/controllers/utils.go
  pkg/kwokctl/cmd/root.go
  pkg/kwokctl/cmd/scale/scale.go
  pkg/kwokctl/scale/doc.go
  pkg/kwokctl/scale/scale.go
  pkg/utils/expression/query_test.go
  pkg/utils/net/ip.go
  pkg/utils/net/ip_test.go
  site/content/en/docs/generated/apis.md
  site/content/en/docs/generated/kwokctl.md
  site/content/en/docs/generated/kwokctl_scale.md
  test/kwokctl/helper.sh
  test/kwokctl/kwokctl_benchmark_test.sh
  test/kwokctl/kwokctl_workable_test.sh
Labels: kind/feature, size/XXL, approved, kind/documentation, kind/api-change, cncf-cla: yes, release-note

#727 [doc] Fix example for argo
  site/content/en/docs/examples/argo.md
Labels: approved, kind/documentation, size/XS, cncf-cla: yes, release-note-none

#728 Bump go.mod
  go.mod
  go.sum
Labels: approved, kind/cleanup, cncf-cla: yes, size/M, release-note-none

#729 Install kustomize with source code to avoid Github request rate limit.
  go.mod
  go.sum
  hack/requirements.sh
  hack/tools/tools.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/M, release-note-none

#730 Add release manifests stage-fast.yaml and kwokctl.yaml
  Makefile
  hack/manifests.sh
  kustomize/stage/fast/kustomization.yaml
  kustomize/stage/node/fast/README.md
  kustomize/stage/node/fast/kustomization.yaml
  kustomize/stage/node/fast/node-initialize.yaml
  kustomize/stage/node/heartbeat/README.md
  kustomize/stage/node/heartbeat/kustomization.yaml
  kustomize/stage/node/heartbeat/node-heartbeat.yaml
  kustomize/stage/pod/fast/README.md
  kustomize/stage/pod/fast/kustomization.yaml
  kustomize/stage/pod/fast/pod-complete.yaml
  kustomize/stage/pod/fast/pod-delete.yaml
  kustomize/stage/pod/fast/pod-ready.yaml
  kustomize/stage/pod/general/README.md
  kustomize/stage/pod/general/kustomization.yaml
  kustomize/stage/pod/general/pod-complete.yaml
  kustomize/stage/pod/general/pod-create.yaml
  kustomize/stage/pod/general/pod-delete.yaml
  kustomize/stage/pod/general/pod-init-container-completed.yaml
  kustomize/stage/pod/general/pod-init-container-running.yaml
  kustomize/stage/pod/general/pod-ready.yaml
  kustomize/stage/pod/general/pod-remove-finalizer.yaml
  site/content/en/docs/user/stages-configuration.md
  test/release/build.test.sh
Labels: kind/feature, size/XL, approved, kind/documentation, cncf-cla: yes, release-note

#736 No filter support for load yaml
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/scale/scale.go
  pkg/kwokctl/snapshot/load.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/M, release-note-none

#739 Support CRD for Metric
  pkg/config/resources/dynamic.go
  pkg/config/resources/resource.go
  pkg/kwok/cmd/root.go
  pkg/kwok/metrics/cel/evaluate.go
  pkg/kwok/metrics/metrics.go
  pkg/kwok/server/metrics.go
  pkg/kwok/server/server.go
Labels: approved, cncf-cla: yes, release-note, size/L

#745 [kwokctl] Add user option for components
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/compose/self_compose.go
  site/content/en/docs/generated/apis.md
Labels: kind/feature, approved, kind/documentation, kind/api-change, cncf-cla: yes, release-note, size/M
