Repository kubernetes-sigs/kwok, pull requests merged in 2023-04, with the labels that each got.

#439 [kwokctl] Support ExtraVolumes and refactor ExtraArgs
  .github/workflows/test.yaml
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/kwokctl/components/etcd.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/components/kube_controller_manager.go
  pkg/kwokctl/components/kube_scheduler.go
  pkg/kwokctl/components/kwok_controller.go
  pkg/kwokctl/components/prometheus.go
  pkg/kwokctl/components/utils.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/kind.go
  pkg/kwokctl/runtime/kind/kind.yaml.tpl
  pkg/kwokctl/runtime/kind/kwok_controller_pod.go
  pkg/kwokctl/runtime/kind/kwok_controller_pod.yaml.tpl
  pkg/kwokctl/runtime/kind/prometheus_deployment.go
  pkg/kwokctl/runtime/kind/prometheus_deployment.yaml.tpl
  pkg/kwokctl/runtime/util.go
  test/kwokctl/fake-kwok-config-le-1-17.yaml
  test/kwokctl/fake-kwok-config.yaml
  test/kwokctl/kwokctl-config-patches.yaml
  test/kwokctl/kwokctl_binary_extra.test.sh
  test/kwokctl/kwokctl_docker_extra.test.sh
  test/kwokctl/kwokctl_extra_test.sh
  test/kwokctl/kwokctl_kind_extra.test.sh
  test/kwokctl/kwokctl_nerdctl_extra.test.sh
  test/kwokctl/kwokctl_workable_test.sh
Labels: kind/feature, size/XL, approved, cncf-cla: yes

#446 Fix exec with tty
  go.mod
  go.sum
  pkg/kwok/server/debugging_exec.go
  pkg/kwok/server/debugging_exec_other.go
  pkg/kwok/server/debugging_exec_windows.go
  pkg/utils/exec/exec.go
  test/kwokctl/kwokctl_exec_test.sh
Labels: kind/bug, approved, cncf-cla: yes, size/M

#438 Switched from N1 to E2 machine
  cloudbuild.yaml
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#447 Fix flake
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/cluster_snapshot.go
  test/kwokctl/kwokctl_exec_test.sh
  test/kwokctl/kwokctl_extra_test.sh
  test/kwokctl/kwokctl_multi_cluster_test.sh
  test/kwokctl/kwokctl_port_forward_test.sh
  test/kwokctl/kwokctl_scheduler_test.sh
  test/kwokctl/kwokctl_snapshot_test.sh
  test/kwokctl/kwokctl_workable_test.sh
Labels: approved, kind/failing-test, cncf-cla: yes, size/L

#422 Enable admission plugins
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/config/vars.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
  site/content/en/docs/user/kwokctl-admission.md
  site/content/en/docs/user/kwokctl-authorization.md
  site/content/en/menu/index.md
  test/kwokctl/kwokctl_workable_test.sh
Labels: kind/feature, approved, cncf-cla: yes, size/L

#452 [doc] Add kwokctl metrics
  site/content/en/docs/user/kwokctl-metrics.md
  site/content/en/menu/index.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/M

#455 Include kwok controller extra mounts in kind and add support to relative paths to volumes
  .github/workflows/test.yaml
  .golangci.yaml
  pkg/config/config_test.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/kind.go
  pkg/kwokctl/runtime/kind/kind.yaml.tpl
  pkg/kwokctl/runtime/kind/kwok_controller_pod.go
  pkg/kwokctl/runtime/kind/prometheus_deployment.go
  pkg/kwokctl/runtime/util.go
  test/kwokctl/kwokctl-config-patches.yaml
  test/kwokctl/kwokctl_extra_test.sh
Labels: kind/feature, ok-to-test, tide/merge-method-squash, approved, cncf-cla: yes, lgtm, size/L

#451 Add why kwok to ReadME
  README.md
  site/content/en/_index.md
Labels: tide/merge-method-squash, approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#308 Pass Verbosity to all components
  .github/workflows/test.yaml
  pkg/kwokctl/components/etcd.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/components/kube_controller_manager.go
  pkg/kwokctl/components/kube_scheduler.go
  pkg/kwokctl/components/prometheus.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/kind.go
  pkg/kwokctl/runtime/kind/prometheus_deployment.go
  pkg/kwokctl/runtime/kind/prometheus_deployment.yaml.tpl
  pkg/log/convert.go
  pkg/log/logger.go
  pkg/log/logger_noop.go
  pkg/log/wrapper.go
  test/kwokctl/kwokctl_binary_verbosity.test.sh
  test/kwokctl/kwokctl_docker_verbosity.test.sh
  test/kwokctl/kwokctl_kind_verbosity.test.sh
  test/kwokctl/kwokctl_nerdctl_verbosity.test.sh
  test/kwokctl/kwokctl_verbosity_test.sh
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L

#450 Refactor snapshot for format k8s
  pkg/kwokctl/cmd/snapshot/export/export.go
  pkg/kwokctl/cmd/snapshot/snapshot.go
  pkg/kwokctl/runtime/cluster_snapshot.go
  pkg/kwokctl/snapshot/load.go
  pkg/kwokctl/snapshot/load_test.go
  pkg/kwokctl/snapshot/runtime.go
  pkg/kwokctl/snapshot/save.go
  pkg/utils/client/client.go
  pkg/utils/client/doc.go
  pkg/utils/client/lazyrestmapper.go
  pkg/utils/yaml/decoder.go
  pkg/utils/yaml/decoder_test.go
  pkg/utils/yaml/doc.go
  pkg/utils/yaml/encoder.go
  pkg/utils/yaml/encoder_test.go
  site/content/en/docs/generated/kwokctl.md
  site/content/en/docs/generated/kwokctl_snapshot.md
  site/content/en/docs/generated/kwokctl_snapshot_export.md
  site/content/en/docs/generated/kwokctl_snapshot_restore.md
  site/content/en/docs/generated/kwokctl_snapshot_save.md
  site/content/en/docs/user/kwokctl-snapshot.md
Labels: size/XXL, approved, kind/cleanup, cncf-cla: yes, lgtm

#457 snapshot: add limitrange, priorityclass and runtimeclass to default resources
  pkg/kwokctl/snapshot/runtime.go
  site/content/en/docs/generated/kwokctl_snapshot_export.md
  site/content/en/docs/generated/kwokctl_snapshot_restore.md
  site/content/en/docs/generated/kwokctl_snapshot_save.md
Labels: approved, kind/cleanup, size/S, kind/documentation, cncf-cla: yes, lgtm

#458 snapshot: impose retry logic
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/cluster_snapshot.go
  pkg/kwokctl/snapshot/load.go
  pkg/kwokctl/snapshot/save.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M

#462 snapshot: add --as and --as-group to support impersonation
  pkg/kwokctl/cmd/snapshot/export/export.go
  pkg/kwokctl/runtime/cluster_snapshot.go
  pkg/kwokctl/snapshot/save.go
  site/content/en/docs/generated/kwokctl_snapshot_export.md
Labels: kind/feature, approved, size/S, cncf-cla: yes, lgtm

#415 [kwok] Add ImmediateNextStage for Stage
  pkg/apis/internalversion/stage_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/v1alpha1/stage_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/kwok/controllers/lifecycle.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/utils.go
  site/content/en/docs/user/stages-configuration.md
  stages/node-fast.yaml
Labels: kind/feature, approved, kind/api-change, cncf-cla: yes, size/L

#464 Clean up logs info
  pkg/kwokctl/cmd/delete/cluster/cluster.go
  pkg/kwokctl/cmd/get/kubeconfig/kubeconfig.go
  pkg/kwokctl/cmd/kubectl/kubectl.go
  pkg/kwokctl/cmd/logs/logs.go
  pkg/kwokctl/cmd/snapshot/restore/restore.go
  pkg/kwokctl/cmd/snapshot/save/save.go
  pkg/kwokctl/cmd/start/cluster/cluster.go
  pkg/kwokctl/cmd/stop/cluster/cluster.go
Labels: approved, kind/documentation, cncf-cla: yes, size/M

#461 Clean up client set
  pkg/kwok/cmd/root.go
  pkg/kwokctl/snapshot/load.go
  pkg/kwokctl/snapshot/save.go
  pkg/utils/client/client.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#465 Allows no kubeconfig to be set for cluster create
  pkg/kwokctl/cmd/create/cluster/cluster.go
Labels: kind/bug, approved, size/S, cncf-cla: yes

#468 Optimising the snapshot experience
  pkg/kwokctl/cmd/snapshot/export/export.go
  pkg/kwokctl/cmd/snapshot/restore/restore.go
  pkg/kwokctl/snapshot/load.go
  pkg/kwokctl/snapshot/runtime.go
  pkg/kwokctl/snapshot/save.go
  site/content/en/docs/generated/kwokctl_snapshot_export.md
  site/content/en/docs/generated/kwokctl_snapshot_restore.md
  site/content/en/docs/generated/kwokctl_snapshot_save.md
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#475 fix get port used
  pkg/utils/net/unused_port.go
Labels: kind/bug, ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#417 [kwok] Provided service for logs
  .github/workflows/test.yaml
  go.mod
  go.sum
  pkg/apis/internalversion/cluster_logs_types.go
  pkg/apis/internalversion/conversion.go
  pkg/apis/internalversion/logs_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/cluster_logs_types.go
  pkg/apis/v1alpha1/logs_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/config/config.go
  pkg/kwok/cmd/root.go
  pkg/kwok/server/debugging_logs.go
  pkg/kwok/server/server.go
  pkg/kwokctl/components/kwok_controller.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/kwok_controller_pod.yaml.tpl
  pkg/kwokctl/runtime/util.go
  pkg/utils/tail/tail.go
  test/kwokctl/kwokctl_binary_logs.test.sh
  test/kwokctl/kwokctl_docker_logs.test.sh
  test/kwokctl/kwokctl_kind_logs.test.sh
  test/kwokctl/kwokctl_logs_test.sh
  test/kwokctl/kwokctl_nerdctl_logs.test.sh
  test/kwokctl/logs.yaml
Labels: kind/feature, ok-to-test, size/XXL, tide/merge-method-squash, approved, cncf-cla: yes, lgtm

#486 Bump k8s to 1.27
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
  go.mod
  go.sum
  hack/gen_cmd_docs/main.go
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/controller_test.go
  pkg/kwokctl/cmd/get/artifacts/artifacts.go
  pkg/kwokctl/cmd/get/clusters/clusters.go
  pkg/kwokctl/pki/pkiutil.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/binary/cluster_snapshot.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/cluster_snapshot.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/cluster_snapshot.go
  pkg/utils/net/unused_port.go
  pkg/utils/wait/wait.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#487 Bump go to 1.20
  .github/workflows/golangci-lint.yaml
  .github/workflows/releases.yaml
  .github/workflows/test.yaml
  .golangci.yaml
  go.mod
Labels: approved, kind/cleanup, size/S, cncf-cla: yes

#460 Add shellcheck to lint shell scripts
  hack/verify-all.sh
  hack/verify-shellcheck.sh
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L

#490 [kwokctl] Bump dependent components
  pkg/consts/consts.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
Labels: kind/feature, ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#491 Fix SC2034 for shellcheck
  hack/verify-shellcheck.sh
  test/kwok-with-cni/kwok-with-cni.test.sh
  test/kwok/kwok.test.sh
  test/kwokctl/kwokctl_extra_test.sh
Labels: approved, kind/cleanup, size/S, cncf-cla: yes, lgtm

#493 Fix SC2294 for shellcheck
  hack/releases.sh
  hack/verify-shellcheck.sh
  images/cluster/build.sh
  images/kwok/build.sh
Labels: approved, kind/cleanup, size/S, cncf-cla: yes, lgtm

#492 Fix SC2002 for shellcheck
  demo/play-demo.sh
  hack/verify-shellcheck.sh
  test/kwokctl/helper.sh
  test/kwokctl/kwokctl_logs_test.sh
Labels: approved, kind/cleanup, size/S, cncf-cla: yes, lgtm

#497 Fix SC2126 for shellcheck
  hack/verify-shellcheck.sh
  test/kwok-with-cni/kwok-with-cni.test.sh
  test/kwok/kwok.test.sh
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#503 fix verbosity test failed
  test/kwokctl/kwokctl_verbosity_test.sh
Labels: kind/bug, approved, size/XS, cncf-cla: yes, lgtm

#402 Automated cherry pick of #400: Fixes node not initialized
  stages/node-fast.yaml
Labels: approved, size/XS, cncf-cla: yes

#441 Automated cherry pick of #440: Fix featureGates and runtimeConfig on kind runtime
  pkg/kwokctl/runtime/kind/kind.yaml.tpl
Labels: approved, size/XS, cncf-cla: yes

#479 Automated cherry pick of #475: fix get port used
  pkg/utils/net/unused_port.go
Labels: approved, size/S, cncf-cla: yes

#507 Bump etcd
  pkg/kwokctl/k8s/etcd.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
Labels: approved, kind/cleanup, size/S, cncf-cla: yes

#496 Fix SC2053 for shellcheck
  hack/verify-shellcheck.sh
  test/kwok/kwok.test.sh
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#518 Fix wait
  pkg/kwok/controllers/controller_test.go
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/utils/wait/wait.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/M

#517 Bump k8s 1.27.0 to 1.27.1
  go.mod
  go.sum
Labels: approved, kind/cleanup, cncf-cla: yes, size/M

#498 Fix SC2009 for shellcheck
  hack/verify-shellcheck.sh
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#504 Fix SC2069 for shellcheck
  hack/verify-shellcheck.sh
  test/kwokctl/kwokctl_port_forward_test.sh
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#515 [kwok] Provide service for `attach`
  .github/workflows/test.yaml
  pkg/apis/internalversion/attach_types.go
  pkg/apis/internalversion/cluster_attach_types.go
  pkg/apis/internalversion/conversion.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/attach_types.go
  pkg/apis/v1alpha1/cluster_attach_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/config/config.go
  pkg/kwok/cmd/root.go
  pkg/kwok/server/debugging_attach.go
  pkg/kwok/server/debugging_logs.go
  pkg/kwok/server/server.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/util.go
  test/kwokctl/attach.yaml
  test/kwokctl/kwokctl_attach_test.sh
  test/kwokctl/kwokctl_binary_attach.test.sh
  test/kwokctl/kwokctl_docker_attach.test.sh
  test/kwokctl/kwokctl_kind_attach.test.sh
  test/kwokctl/kwokctl_nerdctl_attach.test.sh
Labels: kind/feature, ok-to-test, size/XXL, tide/merge-method-squash, approved, cncf-cla: yes, lgtm

#523 Clean up utilities about versions
  pkg/config/vars.go
  pkg/kwok/cmd/root.go
  pkg/kwokctl/cmd/root.go
  pkg/utils/client/client.go
  pkg/utils/version/prefix.go
  pkg/utils/version/vars.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#525 Fix flake test
  test/kwokctl/helper.sh
  test/kwokctl/kwokctl_attach_test.sh
  test/kwokctl/kwokctl_audit_test.sh
  test/kwokctl/kwokctl_authorization_test.sh
  test/kwokctl/kwokctl_auto_detect.test.sh
  test/kwokctl/kwokctl_benchmark_test.sh
  test/kwokctl/kwokctl_exec_test.sh
  test/kwokctl/kwokctl_extra_test.sh
  test/kwokctl/kwokctl_logs_test.sh
  test/kwokctl/kwokctl_multi_cluster_test.sh
  test/kwokctl/kwokctl_port_forward_test.sh
  test/kwokctl/kwokctl_restart_test.sh
  test/kwokctl/kwokctl_scheduler_test.sh
  test/kwokctl/kwokctl_snapshot_test.sh
  test/kwokctl/kwokctl_verbosity_test.sh
  test/kwokctl/kwokctl_workable_test.sh
Labels: approved, cncf-cla: yes, kind/flake, size/L

#524 Bump nerdctl on ci
  .github/workflows/test.yaml
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes

#519 Fix SC2086 for shellcheck
  hack/supported_releases.sh
  hack/verify-shellcheck.sh
  test/kwok/kwok.test.sh
  test/kwokctl/helper.sh
  test/kwokctl/kwokctl_verbosity_test.sh
Labels: ok-to-test, approved, kind/cleanup, size/S, cncf-cla: yes, lgtm

#526 Clean up test
  test/kwokctl/helper.sh
  test/kwokctl/kwokctl_attach_test.sh
  test/kwokctl/kwokctl_audit_test.sh
  test/kwokctl/kwokctl_authorization_test.sh
  test/kwokctl/kwokctl_benchmark_test.sh
  test/kwokctl/kwokctl_exec_test.sh
  test/kwokctl/kwokctl_extra_test.sh
  test/kwokctl/kwokctl_logs_test.sh
  test/kwokctl/kwokctl_multi_cluster_test.sh
  test/kwokctl/kwokctl_port_forward_test.sh
  test/kwokctl/kwokctl_restart_test.sh
  test/kwokctl/kwokctl_scheduler_test.sh
  test/kwokctl/kwokctl_snapshot_test.sh
  test/kwokctl/kwokctl_verbosity_test.sh
  test/kwokctl/kwokctl_workable_test.sh
  test/kwokctl/suite.sh
Labels: size/XL, approved, kind/cleanup, cncf-cla: yes

#521 fix(kind cleanup): fix task SC2015
  hack/e2e-test.sh
  hack/releases.sh
  hack/verify-shellcheck.sh
  images/cluster/build.sh
  images/kwok/build.sh
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/M

#501 Fix SC2155 for shellcheck
  hack/verify-shellcheck.sh
  test/kwokctl/kwokctl_attach_test.sh
  test/kwokctl/kwokctl_logs_test.sh
Labels: ok-to-test, approved, kind/cleanup, size/S, cncf-cla: yes, lgtm

#434 [doc] Add docs of node service
  .gitignore
  demo/attach.demo
  demo/attach.svg
  demo/exec.demo
  demo/exec.svg
  demo/logs.demo
  demo/logs.svg
  demo/port-forward.demo
  demo/port-forward.svg
  site/content/en/docs/user/attach-configuration.md
  site/content/en/docs/user/exec-configuration.md
  site/content/en/docs/user/logs-configuration.md
  site/content/en/docs/user/port-forward-configuration.md
  site/content/en/docs/user/stages-configuration.md
  site/content/en/menu/index.md
  site/static/img/demo/attach.svg
  site/static/img/demo/exec.svg
  site/static/img/demo/logs.svg
  site/static/img/demo/port-forward.svg
Labels: approved, kind/documentation, cncf-cla: yes, size/L

#506 Update demo
  demo/Makefile
  demo/audit-log.demo
  demo/audit-log.svg
  demo/manage-clusters.demo
  demo/manage-clusters.svg
  demo/stages-pod-fast.demo
  demo/stages-pod-fast.svg
  demo/stages-pod-general.demo
  demo/stages-pod-general.svg
Labels: approved, kind/documentation, cncf-cla: yes, size/M

#522 Version 0.2.0
  pkg/consts/consts.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
Labels: kind/feature, approved, kind/cleanup, size/S, cncf-cla: yes

#528 Update docs
  README.md
  site/content/en/_index.md
  site/content/en/docs/adopters/_index.md
  site/content/en/docs/user/all-in-one-image.md
  site/content/en/docs/user/attach-configuration.md
  site/content/en/docs/user/configuration.md
  site/content/en/docs/user/exec-configuration.md
  site/content/en/docs/user/getting-started.md
  site/content/en/docs/user/install.md
  site/content/en/docs/user/kwok-out-cluster.md
  site/content/en/docs/user/kwokctl-manage-cluster.md
  site/content/en/docs/user/kwokctl-snapshot.md
  site/content/en/docs/user/logs-configuration.md
  site/content/en/docs/user/port-forward-configuration.md
  site/content/en/docs/user/stages-configuration.md
  site/content/en/menu/index.md
Labels: approved, kind/documentation, cncf-cla: yes, size/L

#542 Fix error template value for node-fast.yaml
  stages/node-fast.yaml
Labels: kind/bug, ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#543 Automated cherry pick of #542: Fix error template value for node-fast.yaml
  stages/node-fast.yaml
Labels: approved, size/XS, cncf-cla: yes, lgtm

#551 Fix hugo version check
  .github/workflows/test.yaml
  site/Makefile
Labels: approved, kind/cleanup, kind/failing-test, size/S, cncf-cla: yes, lgtm

#552 Automated cherry pick of #551: Fix hugo version check
  .github/workflows/test.yaml
  site/Makefile
Labels: approved, size/S, cncf-cla: yes

#535 Allows test on macos with binary
  .github/workflows/test.yaml
Labels: approved, kind/cleanup, cncf-cla: yes, size/M

#549 🐛 Suppress downloading binaries when `--disable-kube*` is specified
  pkg/kwokctl/runtime/binary/cluster.go
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm

#546 Fix SC2076 for shellcheck
  hack/supported_releases.sh
  hack/verify-shellcheck.sh
  test/kwok/kwok.test.sh
  test/kwokctl/kwokctl_attach_test.sh
  test/kwokctl/kwokctl_exec_test.sh
  test/kwokctl/kwokctl_logs_test.sh
Labels: ok-to-test, approved, kind/cleanup, size/S, cncf-cla: yes, lgtm

#534 Make KwokBinaryPrefix consistent with the rest in KwokConfiguration
  pkg/config/vars.go
Labels: kind/feature, approved, kind/api-change, size/XS, cncf-cla: yes, lgtm
