Repository kubernetes-sigs/kwok, pull requests merged in 2023-01, with the labels that each got.

#190 Fix e2e
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/zz_generated.defaults.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
Labels: kind/feature, approved, kind/failing-test, cncf-cla: yes, size/M

#191 Use different args based on version
  .github/workflows/cron-test.yaml
  .github/workflows/test.yaml
  .golangci.yaml
  go.mod
  go.sum
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/v1alpha1/kwokctl_configuration_types.go
  pkg/config/vars.go
  pkg/kwokctl/components/etcd.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/components/kube_controller_manager.go
  pkg/kwokctl/components/kube_scheduler.go
  pkg/kwokctl/components/kwok_controller.go
  pkg/kwokctl/components/prometheus.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/utils/version/version.go
  pkg/utils/version/version_test.go
  test/kwokctl/helper.sh
Labels: kind/feature, approved, cncf-cla: yes, size/L

#192 Fix snapshot of runtime nerdctl
  .github/workflows/test.yaml
  pkg/kwokctl/runtime/compose/cluster_snapshot.go
  site/content/en/_index.md
Labels: kind/bug, approved, cncf-cla: yes, size/M

#194 Clean ci
  .github/workflows/bump_releases.yaml
  .github/workflows/releases.yaml
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes

#193 Bump Prometheus to 2.41.0
  pkg/consts/consts.go
Labels: kind/feature, ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#196 Fix isRunning
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
Labels: kind/bug, approved, cncf-cla: yes, size/M

#172 fix gosec in golangci.yaml
  .golangci.yaml
  pkg/cni/netns_linux.go
  pkg/config/config.go
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/utils/exec/cmd.go
  pkg/utils/file/download.go
  pkg/utils/file/file.go
  pkg/utils/file/untar.go
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/M

#195 Update docs
  demo/audit-log.demo
  demo/audit-log.svg
  pkg/kwokctl/cmd/logs/logs.go
  site/content/en/docs/user/kwokctl-auditing.md
  site/content/en/menu/index.md
  site/static/audit-log.svg
Labels: approved, kind/documentation, cncf-cla: yes, size/M

#74 Support Pod/Node lifecycle simulation
  demo/stages-pod-fast.demo
  demo/stages-pod-fast.svg
  demo/stages-pod-general.demo
  demo/stages-pod-general.svg
  go.mod
  go.sum
  pkg/apis/internalversion/conversion.go
  pkg/apis/internalversion/stage_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/stage_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/zz_generated.defaults.go
  pkg/config/config.go
  pkg/config/vars.go
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/finalizers.go
  pkg/kwok/controllers/finalizers_test.go
  pkg/kwok/controllers/lifecycle.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/kwok/controllers/templates/node.heartbeat.tpl
  pkg/kwok/controllers/templates/node.status.tpl
  pkg/kwok/controllers/templates/pod.status.tpl
  pkg/utils/expression/query.go
  pkg/utils/expression/query_test.go
  pkg/utils/expression/selector.go
  pkg/utils/expression/value_from.go
  pkg/utils/expression/value_from_test.go
  pkg/utils/slices/slices.go
  site/content/en/docs/user/stages-configuration.md
  site/content/en/menu/index.md
  site/static/stages-pod-fast.svg
  site/static/stages-pod-general.svg
  stages/embed.go
  stages/node-fast.yaml
  stages/pod-fast.yaml
  stages/pod-general.yaml
  test/lifecycle/fake-node.yaml
  test/lifecycle/fake-pod-stages.yaml
Labels: kind/feature, size/XXL, approved, cncf-cla: yes

#198 Kwok's Kubelet service stubs
  go.mod
  go.sum
  kustomize/kwok-with-cni/kwok-deployment-patch.yaml
  kustomize/kwok/kwok-deployment.yaml
  pkg/apis/internalversion/kwok_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/v1alpha1/kwok_configuration_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/zz_generated.defaults.go
  pkg/config/vars.go
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/server/convert.go
  pkg/kwok/server/debugging.go
  pkg/kwok/server/debugging_attach.go
  pkg/kwok/server/debugging_exec.go
  pkg/kwok/server/debugging_logs.go
  pkg/kwok/server/debugging_port_forword.go
  pkg/kwok/server/healthz.go
  pkg/kwok/server/metrics.go
  pkg/kwok/server/portforward/constants.go
  pkg/kwok/server/portforward/httpstream.go
  pkg/kwok/server/portforward/httpstream_test.go
  pkg/kwok/server/portforward/portforward.go
  pkg/kwok/server/portforward/websocket.go
  pkg/kwok/server/portforward/websocket_test.go
  pkg/kwok/server/profiling.go
  pkg/kwok/server/remotecommand/attach.go
  pkg/kwok/server/remotecommand/constants.go
  pkg/kwok/server/remotecommand/doc.go
  pkg/kwok/server/remotecommand/exec.go
  pkg/kwok/server/remotecommand/httpstream.go
  pkg/kwok/server/remotecommand/websocket.go
  pkg/kwok/server/server.go
  pkg/kwokctl/components/kwok_controller.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/prometheus.yaml.tpl
  pkg/kwokctl/runtime/kind/kwok_controller_pod.yaml.tpl
  pkg/kwokctl/runtime/kind/prometheus_deployment.yaml.tpl
  stages/node-fast.yaml
Labels: kind/feature, size/XXL, approved, cncf-cla: yes

#203 Cleanup cni
  pkg/apis/internalversion/kwok_configuration_types.go
  pkg/apis/v1alpha1/kwok_configuration_types.go
  pkg/kwok/cmd/root.go
  pkg/kwok/cni/cni_linux.go
  pkg/kwok/cni/cni_other.go
  pkg/kwok/cni/netns_linux.go
  pkg/kwok/controllers/pod_controller.go
Labels: approved, kind/cleanup, size/S, cncf-cla: yes

#201 Add --kube-scheduler-config for kwokctl
  .github/workflows/test.yaml
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/v1alpha1/kwokctl_configuration_types.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/components/kube_scheduler.go
  pkg/kwokctl/k8s/scheduler.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/kind.go
  pkg/kwokctl/runtime/kind/kind.yaml.tpl
  pkg/utils/file/file.go
  test/kwokctl/fake-scheduler-deployment.yaml
  test/kwokctl/kwokctl_binary_scheduler.test.sh
  test/kwokctl/kwokctl_docker_scheduler.test.sh
  test/kwokctl/kwokctl_kind_scheduler.test.sh
  test/kwokctl/kwokctl_nerdctl_scheduler.test.sh
  test/kwokctl/kwokctl_scheduler_test.sh
  test/kwokctl/scheduler-config.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/L

#205 Provide all-in-one images
  cloudbuild.yaml
Labels: kind/feature, approved, kind/cleanup, size/XS, cncf-cla: yes

#207 Build only the cluster image of the last 6 releases
  Makefile
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes

#206 add dependabot in github-actions
  .github/workflows/dependabot.yml
Labels: approved, size/S, cncf-cla: yes, lgtm

#209 Fix dependabot
  .github/dependabot.yml
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes

#208 Update dockerfile
  .github/workflows/test.yaml
  Makefile
  images/cluster/Dockerfile
  images/kwok/Dockerfile
Labels: approved, kind/cleanup, cncf-cla: yes, size/M

#214 modify some comments for consistency
  pkg/kwok/cni/cni_linux.go
  pkg/kwok/cni/netns_linux.go
Labels: ok-to-test, approved, kind/documentation, cncf-cla: yes, lgtm, size/M

#215 Units as part of the field name for the duration field
  pkg/apis/internalversion/stage_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/stage_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/config/config_test.go
  pkg/kwok/controllers/lifecycle.go
  site/content/en/docs/user/stages-configuration.md
  stages/node-fast.yaml
  stages/pod-general.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L

#219 update CONTRIBUTING.md by following template
  CONTRIBUTING.md
Labels: ok-to-test, approved, kind/documentation, size/XS, cncf-cla: yes, lgtm

#220 Update website
  README.md
  netlify.toml
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#218 Add docs for all-in-one image
  site/content/en/docs/user/all-in-one-image.md
  site/content/en/menu/index.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/M

#223 update dependabot's version check to weekly
  .github/dependabot.yml
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#238 Refactoring the Kubelet Service interface
  pkg/kwok/server/debugging_attach.go
  pkg/kwok/server/debugging_exec.go
  pkg/kwok/server/debugging_logs.go
  pkg/kwok/server/debugging_port_forword.go
  pkg/kwok/server/portforward/httpstream.go
  pkg/kwok/server/portforward/portforward.go
  pkg/kwok/server/portforward/websocket.go
  pkg/kwok/server/remotecommand/attach.go
  pkg/kwok/server/remotecommand/exec.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#239 Clean up kwokctl tests
  test/kwokctl/helper.sh
  test/kwokctl/kwokctl_authorization_test.sh
  test/kwokctl/kwokctl_binary.test.sh
  test/kwokctl/kwokctl_binary_audit.test.sh
  test/kwokctl/kwokctl_binary_authorization.test.sh
  test/kwokctl/kwokctl_binary_benchmark.test.sh
  test/kwokctl/kwokctl_binary_restart.test.sh
  test/kwokctl/kwokctl_binary_scheduler.test.sh
  test/kwokctl/kwokctl_binary_snapshot.test.sh
  test/kwokctl/kwokctl_docker.test.sh
  test/kwokctl/kwokctl_docker_audit.test.sh
  test/kwokctl/kwokctl_docker_authorization.test.sh
  test/kwokctl/kwokctl_docker_benchmark.test.sh
  test/kwokctl/kwokctl_docker_restart.test.sh
  test/kwokctl/kwokctl_docker_scheduler.test.sh
  test/kwokctl/kwokctl_docker_snapshot.test.sh
  test/kwokctl/kwokctl_kind.test.sh
  test/kwokctl/kwokctl_kind_audit.test.sh
  test/kwokctl/kwokctl_kind_authorization.test.sh
  test/kwokctl/kwokctl_kind_benchmark.test.sh
  test/kwokctl/kwokctl_kind_restart.test.sh
  test/kwokctl/kwokctl_kind_scheduler.test.sh
  test/kwokctl/kwokctl_kind_snapshot.test.sh
  test/kwokctl/kwokctl_nerdctl.test.sh
  test/kwokctl/kwokctl_nerdctl_audit.test.sh
  test/kwokctl/kwokctl_nerdctl_authorization.test.sh
  test/kwokctl/kwokctl_nerdctl_benchmark.test.sh
  test/kwokctl/kwokctl_nerdctl_restart.test.sh
  test/kwokctl/kwokctl_nerdctl_scheduler.test.sh
  test/kwokctl/kwokctl_nerdctl_snapshot.test.sh
  test/kwokctl/kwokctl_scheduler_test.sh
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#240 Uniformly short starts with a capital letter
  pkg/kwok/cmd/root.go
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm
