Repository kubernetes-sigs/kwok, pull requests merged in 2023-06, with the labels that each got.

#633 Optimize the HumanDuration
  pkg/utils/format/duration.go
  pkg/utils/format/duration_test.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/M

#626 fix exec broken pipe error
  test/kwokctl/kwokctl_exec_test.sh
Labels: approved, size/XS, cncf-cla: yes, lgtm

#637 Fix failing test "kwok with cni"
  images/kwok/Dockerfile
  images/kwok/build.sh
  kustomize/kwok-with-cni/kwok-deployment-patch.yaml
  test/kwok-with-cni/kustomization.yaml
  test/kwok-with-cni/kwok-with-cni.test.sh
Labels: approved, kind/failing-test, size/S, cncf-cla: yes

#638 Test the all release of nerdctl
  .github/workflows/test.yaml
Labels: approved, size/S, cncf-cla: yes

#627 Update docs for develop
  site/content/en/_index.md
  site/content/en/docs/contributing/development.md
  site/content/en/docs/user/kwokctl-platform-specific-binaries.md
  site/content/en/menu/index.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/M

#640 Clean up etcd envs
  pkg/kwokctl/components/etcd.go
  pkg/kwokctl/k8s/etcd.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/binary/cluster_snapshot.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/cluster_snapshot.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/cluster_snapshot.go
  pkg/kwokctl/snapshot/load.go
  pkg/kwokctl/snapshot/save.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#635 cleanup usage in build.sh
  images/cluster/build.sh
  images/kwok/build.sh
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#644 Fix flake unit test
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/node_lease_controller.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/utils/version/version.go
  pkg/utils/version/version_test.go
Labels: approved, cncf-cla: yes, kind/flake, size/L

#647 Update menu of site
  site/assets/_custom.scss
  site/config.yaml
  site/content/en/_index.md
  site/content/en/docs/adopters/_index.md
  site/content/en/docs/contributing/_index.md
  site/content/en/docs/contributing/development.md
  site/content/en/docs/contributing/documentation.md
  site/content/en/docs/design/architecture.md
  site/content/en/docs/design/introduction.md
  site/content/en/docs/user/_index.md
  site/content/en/docs/user/all-in-one-image.md
  site/content/en/docs/user/attach-configuration.md
  site/content/en/docs/user/configuration.md
  site/content/en/docs/user/exec-configuration.md
  site/content/en/docs/user/installation.md
  site/content/en/docs/user/kwok-in-cluster.md
  site/content/en/docs/user/kwok-manage-nodes-and-pods.md
  site/content/en/docs/user/kwok-out-cluster.md
  site/content/en/docs/user/kwokctl-admission.md
  site/content/en/docs/user/kwokctl-auditing.md
  site/content/en/docs/user/kwokctl-authorization.md
  site/content/en/docs/user/kwokctl-manage-cluster.md
  site/content/en/docs/user/kwokctl-metrics.md
  site/content/en/docs/user/kwokctl-platform-specific-binaries.md
  site/content/en/docs/user/kwokctl-snapshot.md
  site/content/en/docs/user/logs-configuration.md
  site/content/en/docs/user/port-forward-configuration.md
  site/content/en/docs/user/stages-configuration.md
  site/content/en/menu/index.md
  site/content/en/posts/_index.md
  site/layouts/partials/docs/menu-hugo.html
  site/layouts/partials/docs/menu.html
Labels: approved, kind/documentation, cncf-cla: yes, size/L

#642 [kwokctl] Refactor the pki and the subcommand 'get kubeconfig'
  .golangci.yaml
  pkg/kwok/controllers/finalizers.go
  pkg/kwokctl/cmd/get/kubeconfig/kubeconfig.go
  pkg/kwokctl/components/kube_controller_manager.go
  pkg/kwokctl/components/kube_scheduler.go
  pkg/kwokctl/components/kwok_controller.go
  pkg/kwokctl/k8s/kubeconfig.go
  pkg/kwokctl/k8s/kubeconfig.yaml.tpl
  pkg/kwokctl/pki/pki.go
  pkg/kwokctl/pki/pki_test.go
  pkg/kwokctl/pki/pkiutil.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/binary/cluster_context.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/cluster_context.go
  pkg/kwokctl/runtime/config.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/utils/expression/selector.go
  pkg/utils/kubeconfig/kubeconfig.go
  pkg/utils/net/ip.go
  pkg/utils/slices/slices.go
  site/content/en/docs/generated/kwokctl_get_kubeconfig.md
  test/kwokctl/kwokctl_workable_test.sh
Labels: kind/feature, size/XL, approved, kind/cleanup, cncf-cla: yes

#636 Support for config IP when genegrate pki certificate
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  site/content/en/docs/generated/apis.md
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#643 Update docs of kwokctl support matrix
  site/content/en/_index.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#649 Fix get kubeconfig with user/groups
  pkg/kwokctl/cmd/get/kubeconfig/kubeconfig.go
  pkg/kwokctl/pki/pki.go
Labels: kind/bug, approved, size/XS, cncf-cla: yes

#650 Update runtime support matrix
  site/content/en/_index.md
Labels: approved, kind/documentation, size/XS, cncf-cla: yes

#607 [kwokctl] Support self compose without *-compose
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/compose.go
  pkg/kwokctl/runtime/compose/doc.go
  pkg/kwokctl/runtime/compose/self_compose.go
  pkg/kwokctl/runtime/compose/self_compose_test.go
  pkg/utils/slices/slices.go
  site/content/en/docs/design/architecture.md
  site/content/en/docs/generated/apis.md
  site/content/en/docs/generated/kwokctl_create_cluster.md
Labels: kind/feature, size/XXL, approved, cncf-cla: yes

#651 Clean up the update/verify script
  go.mod
  go.sum
  hack/supported_releases.sh
  hack/tools/tools.go
  hack/update-all.sh
  hack/update-api-docs.sh
  hack/update-cmd-docs.sh
  hack/update-codegen.sh
  hack/update-ends-newline.sh
  hack/update-go-format.sh
  hack/update-go-mod.sh
  hack/update-shell-format.sh
  hack/update-spelling.sh
  hack/verify-all.sh
  hack/verify-api-docs.sh
  hack/verify-boilerplate.sh
  hack/verify-cmd-docs.sh
  hack/verify-codegen.sh
  hack/verify-ends-newline.sh
  hack/verify-go-format.sh
  hack/verify-go-mod.sh
  hack/verify-shell-format.sh
  hack/verify-shellcheck.sh
  hack/verify-spelling.sh
  hack/verify-yamllint.sh
Labels: approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#652 Fix compose flaky test
  pkg/kwokctl/runtime/compose/cluster.go
Labels: approved, cncf-cla: yes, size/M, kind/flake

#555 [kwok] Provide generic functions that enable it to simulate data for any indicator (Node)
  .github/workflows/test.yaml
  go.mod
  go.sum
  pkg/apis/internalversion/conversion.go
  pkg/apis/internalversion/metric_type.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/metric_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/config/config.go
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/kwok/metrics/cel/doc.go
  pkg/kwok/metrics/cel/evaluate.go
  pkg/kwok/metrics/cel/evaluate_test.go
  pkg/kwok/metrics/doc.go
  pkg/kwok/metrics/histogram.go
  pkg/kwok/metrics/histogram_test.go
  pkg/kwok/metrics/metrics.go
  pkg/kwok/server/metrics.go
  pkg/kwok/server/server.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/binary/prometheus.go
  pkg/kwokctl/runtime/binary/prometheus.yaml.tpl
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/prometheus.go
  pkg/kwokctl/runtime/compose/prometheus.yaml.tpl
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/prometheus_deployment.go
  pkg/kwokctl/runtime/kind/prometheus_deployment.yaml.tpl
  pkg/kwokctl/runtime/util.go
  pkg/utils/maps/sync.go
  site/content/en/docs/generated/apis.md
  test/kwokctl/kwokctl_binary_metric.test.sh
  test/kwokctl/kwokctl_docker_metric.test.sh
  test/kwokctl/kwokctl_kind-podman_metric.test.sh
  test/kwokctl/kwokctl_kind_metric.test.sh
  test/kwokctl/kwokctl_metric_test.sh
  test/kwokctl/kwokctl_nerdctl_metric.test.sh
  test/kwokctl/kwokctl_podman_metric.test.sh
  test/kwokctl/metric.yaml
Labels: kind/feature, ok-to-test, size/XXL, approved, cncf-cla: yes, lgtm

#625 add flag --disable-qps-limits
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/consts/consts.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/components/kube_controller_manager.go
  pkg/kwokctl/components/kube_scheduler.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/kind.go
  site/content/en/docs/generated/apis.md
  site/content/en/docs/generated/kwokctl_create_cluster.md
  test/kwokctl/suite.sh
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L

#659 Add demos for docs
  site/config.yaml
  site/content/en/docs/examples/argo.md
  site/content/en/docs/examples/istio.md
  site/content/en/docs/examples/linkerd.md
  site/static/examples/node.yaml
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/L

#655 [kwokctl] Clean up start/stop
  images/cluster/Dockerfile
  images/cluster/entrypoint.sh
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/cmd/delete/cluster/cluster.go
  pkg/kwokctl/components/utils.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/binary/cluster_snapshot.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/compose.go
  pkg/kwokctl/runtime/compose/self_compose.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/cluster_snapshot.go
Labels: size/XL, approved, kind/cleanup, cncf-cla: yes

#639 [kwokctl] Support version skew
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/kwokctl/runtime/cluster.go
  site/content/en/docs/generated/apis.md
Labels: kind/feature, approved, cncf-cla: yes, size/L

#654 Release 0.3.0
  .github/workflows/test.yaml
  go.mod
  go.sum
  hack/requirements.sh
  images/cluster/Dockerfile
  images/kwok/Dockerfile
  pkg/consts/consts.go
  pkg/kwokctl/k8s/etcd.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
  site/content/en/docs/user/kwokctl-platform-specific-binaries.md
Labels: kind/feature, approved, cncf-cla: yes, size/L

#666 Update demo
  demo/attach.svg
  demo/audit-log.svg
  demo/exec.svg
  demo/logs.svg
  demo/manage-clusters.svg
  demo/port-forward.svg
  demo/stages-pod-fast.svg
  demo/stages-pod-general.svg
  site/content/en/docs/user/all-in-one-image.md
Labels: approved, kind/documentation, cncf-cla: yes, size/M

#667 Add release scripts
  demo/OWNERS
  hack/release/.gitignore
  hack/release/get-change-notes.sh
  hack/release/get-contributors.sh
  hack/release/release-notes.sh
  pkg/apis/OWNERS
  site/OWNERS
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#665 [site] Fix site style
  site/assets/_custom.scss
Labels: approved, kind/documentation, cncf-cla: yes, size/M

#679 Fix podman in CI
  .github/workflows/test.yaml
Labels: approved, kind/failing-test, size/S, cncf-cla: yes

#676 Clean up the gotpl
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/pod_controller.go
  pkg/utils/gotpl/doc.go
  pkg/utils/gotpl/renderer.go
  pkg/utils/gotpl/renderer_test.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#673 [kwok] allow numerical container names
  pkg/kwok/controllers/pod_controller_test.go
  stages/pod-fast.yaml
  stages/pod-general.yaml
Labels: kind/bug, ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#684 Support load config from stdin
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/flags.go
  test/kwokctl/kwokctl-config-patches.yaml
  test/kwokctl/kwokctl-config-runtimes.yaml
  test/kwokctl/kwokctl_auto_detect.test.sh
  test/kwokctl/kwokctl_extra_test.sh
Labels: kind/feature, approved, cncf-cla: yes, size/L

#688 Add a quote function for the value of the stage template
  pkg/kwok/controllers/controller.go
  stages/node-fast.yaml
  stages/node-heartbeat.yaml
  stages/pod-fast.yaml
  stages/pod-general.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/L

#687 Fix log of snapshot
  pkg/kwokctl/snapshot/load.go
  pkg/kwokctl/snapshot/save.go
Labels: kind/bug, approved, size/S, cncf-cla: yes

#683 change log path
  .github/workflows/test.yaml
  test/kwokctl/suite.sh
Labels: approved, kind/cleanup, size/S, cncf-cla: yes, lgtm

#690 Clean up clientset
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/controller_test.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwok/controllers/node_lease_controller.go
  pkg/kwok/controllers/node_lease_controller_test.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/kwok/server/server.go
  pkg/kwokctl/snapshot/load.go
  pkg/kwokctl/snapshot/save.go
  pkg/utils/client/clientset.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L
