Repository kubernetes-sigs/kwok, pull requests merged in 2023-05, with the labels that each got.

#547 Add verify-spelling.sh for English words.
  hack/spelling.txt
  hack/update-all.sh
  hack/update-spelling.sh
  hack/verify-all.sh
  hack/verify-spelling.sh
  pkg/kwok/server/debugging_logs.go
  pkg/log/logger_ctl.go
Labels: kind/feature, tide/merge-method-squash, approved, cncf-cla: yes, lgtm, size/L

#561 Fix SC2207 for shellcheck
  hack/e2e-test.sh
  hack/verify-shellcheck.sh
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#558 Update golang.org/x/exp
  go.mod
  go.sum
  hack/gen_cmd_docs/main.go
  pkg/kwok/controllers/controller_test.go
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/components/kube_controller_manager.go
  pkg/kwokctl/components/kube_scheduler.go
  pkg/log/convert.go
  pkg/log/logger.go
  pkg/log/logger_ctl.go
  pkg/log/logger_noop.go
  pkg/log/wrapper.go
  pkg/log/wrapper_test.go
Labels: ok-to-test, tide/merge-method-squash, approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#568 Bump gcb-docker-gcloud
  cloudbuild.yaml
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes

#544 Add the `-alpha` suffix to the version installed with `go install`
  .github/workflows/releases.yaml
  Makefile
  cloudbuild.yaml
  hack/releases.sh
  pkg/consts/consts.go
  pkg/utils/version/vars.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/M

#569 [kwokctl] Fix snapshot on kind runtime
  pkg/kwokctl/runtime/kind/cluster.go
Labels: kind/bug, approved, cncf-cla: yes, size/M

#565 [kwokctl] Fix --wait has no log and cannot be cancelled
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/cmd/start/cluster/cluster.go
Labels: kind/bug, approved, size/XS, cncf-cla: yes

#530 Add clarification docs for differences with other tools
  site/content/en/_index.md
  site/content/en/docs/design/introduction.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#570 [kwokctl] Add podman as the kwokctl runtime
  .github/workflows/test.yaml
  Makefile
  images/cluster/build.sh
  images/kwok/build.sh
  pkg/config/vars.go
  pkg/consts/consts.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/init.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
  site/content/en/docs/generated/kwokctl_get_artifacts.md
  test/kwokctl/helper.sh
  test/kwokctl/kwokctl_podman.test.sh
  test/kwokctl/kwokctl_podman_attach.test.sh
  test/kwokctl/kwokctl_podman_audit.test.sh
  test/kwokctl/kwokctl_podman_authorization.test.sh
  test/kwokctl/kwokctl_podman_benchmark.test.sh
  test/kwokctl/kwokctl_podman_exec.test.sh
  test/kwokctl/kwokctl_podman_extra.test.sh
  test/kwokctl/kwokctl_podman_logs.test.sh
  test/kwokctl/kwokctl_podman_multi_cluster.test.sh
  test/kwokctl/kwokctl_podman_port_forward.test.sh
  test/kwokctl/kwokctl_podman_restart.test.sh
  test/kwokctl/kwokctl_podman_scheduler.test.sh
  test/kwokctl/kwokctl_podman_snapshot.test.sh
  test/kwokctl/kwokctl_podman_verbosity.test.sh
  test/release/build.test.sh
Labels: kind/feature, size/XL, approved, cncf-cla: yes

#574 [kwokctl] Add kind-podman as the kwoctkl runtime
  .github/workflows/test.yaml
  pkg/consts/consts.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/cluster_context.go
  pkg/kwokctl/runtime/kind/cluster_snapshot.go
  pkg/kwokctl/runtime/kind/init.go
  pkg/kwokctl/runtime/kind/kind.yaml.tpl
  pkg/utils/exec/exec.go
  pkg/utils/file/file.go
  pkg/utils/kubeconfig/kubeconfig.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
  site/content/en/docs/generated/kwokctl_get_artifacts.md
  test/kwokctl/helper.sh
  test/kwokctl/kwokctl_kind-podman.test.sh
  test/kwokctl/kwokctl_kind-podman_attach.test.sh
  test/kwokctl/kwokctl_kind-podman_audit.test.sh
  test/kwokctl/kwokctl_kind-podman_authorization.test.sh
  test/kwokctl/kwokctl_kind-podman_benchmark.test.sh
  test/kwokctl/kwokctl_kind-podman_exec.test.sh
  test/kwokctl/kwokctl_kind-podman_extra.test.sh
  test/kwokctl/kwokctl_kind-podman_logs.test.sh
  test/kwokctl/kwokctl_kind-podman_multi_cluster.test.sh
  test/kwokctl/kwokctl_kind-podman_port_forward.test.sh
  test/kwokctl/kwokctl_kind-podman_restart.test.sh
  test/kwokctl/kwokctl_kind-podman_scheduler.test.sh
  test/kwokctl/kwokctl_kind-podman_snapshot.test.sh
  test/kwokctl/kwokctl_kind-podman_verbosity.test.sh
  test/kwokctl/kwokctl_workable_test.sh
Labels: kind/feature, size/XL, approved, cncf-cla: yes

#583 Fix duplicate loading of default configuration
  pkg/config/flags.go
  pkg/config/flags_test.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#576 Clean logs volume on kind runtime
  pkg/apis/internalversion/conversion.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/kwok_controller_pod.yaml.tpl
  pkg/kwokctl/runtime/util.go
  pkg/utils/path/path.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#584 [kwokctl] Fix `-v` argument passing
  pkg/kwokctl/components/etcd.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/components/kube_controller_manager.go
  pkg/kwokctl/components/kube_scheduler.go
  pkg/kwokctl/components/kwok_controller.go
  pkg/kwokctl/components/prometheus.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/kind.go
  pkg/kwokctl/runtime/kind/kwok_controller_pod.go
  pkg/kwokctl/runtime/kind/kwok_controller_pod.yaml.tpl
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/M

#585 Install podman-compose automatically
  .github/workflows/test.yaml
  pkg/kwokctl/runtime/compose/cluster.go
Labels: kind/feature, approved, cncf-cla: yes, size/M

#575 Uniform bind addresses
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/kwok/cmd/root.go
  pkg/kwokctl/components/etcd.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/components/kube_controller_manager.go
  pkg/kwokctl/components/kube_scheduler.go
  pkg/kwokctl/components/kwok_controller.go
  pkg/kwokctl/components/prometheus.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/binary/cluster_context.go
  pkg/kwokctl/runtime/binary/cluster_snapshot.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/cluster_context.go
  pkg/kwokctl/runtime/compose/compose.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/cluster_context.go
  pkg/kwokctl/runtime/kind/cluster_snapshot.go
  pkg/kwokctl/runtime/kind/kind.go
  pkg/utils/net/consts.go
  pkg/utils/net/unused_port.go
  site/content/en/docs/generated/kwok.md
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#571 Automated cherry pick of #569: Fix snapshot on kind runtime
  pkg/kwokctl/runtime/kind/cluster.go
Labels: approved, cncf-cla: yes, size/M

#586 Automated cherry pick of #583: Fix duplicate loading of default configuration
  pkg/config/flags.go
  pkg/config/flags_test.go
Labels: approved, cncf-cla: yes, size/L

#578 Update docs for podman
  pkg/kwokctl/cmd/create/cluster/cluster.go
  site/content/en/_index.md
  site/content/en/docs/design/architecture.md
  site/content/en/docs/generated/kwokctl_create_cluster.md
  site/content/en/docs/user/kwokctl-admission.md
Labels: approved, kind/documentation, cncf-cla: yes, size/M

#449 [kwok] Clean up controller
  pkg/apis/config/v1alpha1/kwok_configuration_types.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/apis/internalversion/kwok_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/controller_test.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/kwok/controllers/utils.go
  pkg/kwok/controllers/utils_test.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#593 Fix default of kwokctl configuration
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/config/vars.go
Labels: kind/bug, approved, size/S, cncf-cla: yes

#590 add version prefix unit test
  pkg/utils/version/prefix_test.go
  pkg/utils/version/vars.go
  pkg/utils/version/vars_test.go
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#599 Update docs
  site/content/en/_index.md
  site/content/en/docs/user/attach-configuration.md
  site/content/en/docs/user/exec-configuration.md
  site/content/en/docs/user/getting-started.md
  site/content/en/docs/user/install.md
  site/content/en/docs/user/kwok-in-cluster.md
  site/content/en/docs/user/kwok-manage-nodes-and-pods.md
  site/content/en/docs/user/kwokctl-auditing.md
  site/content/en/docs/user/logs-configuration.md
  site/content/en/docs/user/port-forward-configuration.md
  site/content/en/docs/user/stages-configuration.md
  site/content/en/menu/index.md
Labels: approved, kind/documentation, cncf-cla: yes, size/L

#560 Fix SC2181 for shellcheck
  hack/verify-shellcheck.sh
  test/kwokctl/kwokctl_attach_test.sh
  test/kwokctl/kwokctl_exec_test.sh
  test/kwokctl/kwokctl_logs_test.sh
  test/kwokctl/kwokctl_port_forward_test.sh
  test/kwokctl/kwokctl_restart_test.sh
  test/kwokctl/kwokctl_verbosity_test.sh
  test/kwokctl/suite.sh
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#587 Add node lease controller
  kustomize/kwok/kwok-clusterrole.yaml
  kustomize/kwok/kwok-deployment.yaml
  pkg/apis/config/v1alpha1/kwok_configuration_types.go
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/apis/internalversion/kwok_configuration_types.go
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/config/vars.go
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/controller_test.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwok/controllers/node_lease_controller.go
  pkg/kwok/controllers/node_lease_controller_test.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/kwokctl/components/kwok_controller.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/kwok_controller_pod.go
  pkg/kwokctl/runtime/kind/kwok_controller_pod.yaml.tpl
  pkg/utils/format/pointer.go
  pkg/utils/wait/wait.go
  site/content/en/docs/generated/kwok.md
  stages/embed.go
  stages/node-fast.yaml
  stages/node-heartbeat.yaml
  test/kwok/kustomization.yaml
  test/kwok/kwok.test.sh
Labels: kind/feature, size/XXL, approved, cncf-cla: yes

#604 disable secure-port before Kubernetes 1.13.0
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/components/kube_controller_manager.go
  pkg/kwokctl/components/kube_scheduler.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
  test/kwokctl/kwokctl_workable_test.sh
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm

#608 Update branch of supported_releases.sh
  hack/supported_releases.sh
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes

#610 Fix preprocess congestion
  pkg/kwok/controllers/node_controller.go
Labels: kind/bug, approved, size/S, cncf-cla: yes

#605 fix update-end-newline
  hack/update-ends-newline.sh
Labels: kind/bug, approved, size/XS, cncf-cla: yes, lgtm

#611 [kwokctl] Clean up the output of get something
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/cmd/get/artifacts/artifacts.go
  pkg/kwokctl/cmd/get/clusters/clusters.go
  pkg/kwokctl/runtime/list.go
  pkg/log/logger.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/M

#614 Optimise output
  go.mod
  go.sum
  pkg/log/convert.go
  pkg/log/logger.go
  pkg/log/logger_ctl.go
  pkg/log/logger_ctl_test.go
  pkg/log/logger_noop.go
  pkg/log/wrapper.go
  pkg/utils/format/duration.go
  pkg/utils/format/duration_test.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#606 enable admission and authorization by default
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/config/vars.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
  site/content/en/docs/user/kwokctl-admission.md
  site/content/en/docs/user/kwokctl-authorization.md
  test/kwokctl/kwokctl_attach_test.sh
  test/kwokctl/kwokctl_exec_test.sh
  test/kwokctl/kwokctl_logs_test.sh
  test/kwokctl/kwokctl_workable_test.sh
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M

#619 feat: support `--page-size` and `--page-buffer-size` for snapshot export and save
  pkg/kwokctl/cmd/snapshot/export/export.go
  pkg/kwokctl/runtime/cluster_snapshot.go
  pkg/kwokctl/snapshot/save.go
  site/content/en/docs/generated/kwokctl_snapshot_export.md
Labels: kind/feature, ok-to-test, tide/merge-method-squash, approved, cncf-cla: yes, lgtm, size/M

#624 Remove required docker-compose
  .github/workflows/test.yaml
  hack/requirements.sh
Labels: approved, kind/cleanup, cncf-cla: yes, size/M

#615 [kwokctl] support all feature-gates
  .github/workflows/test.yaml
  pkg/kwokctl/k8s/feature_gates_data.go
  pkg/kwokctl/k8s/feature_gates_data.sh
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/M
