Repository kubernetes-sigs/kwok, pull requests merged in 2023-02, with the labels that each got.

#243 build: add update-ends-newline.sh to add ends-newline
  hack/update-all.sh
  hack/update-ends-newline.sh
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#250 Fix pprof
  pkg/kwok/server/profiling.go
Labels: kind/bug, approved, size/S, cncf-cla: yes

#249 [kwokctl] Update start/stop for nerdctl
  .github/workflows/test.yaml
  pkg/kwokctl/runtime/compose/cluster.go
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#260 Revert "[kwokctl] Update start/stop for nerdctl"
  .github/workflows/test.yaml
  pkg/kwokctl/runtime/compose/cluster.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#265 Add e2e test to create two clusters for all runtimes
  .github/workflows/test.yaml
  test/kwokctl/kwokctl_binary_multi_cluster.test.sh
  test/kwokctl/kwokctl_docker_multi_cluster.test.sh
  test/kwokctl/kwokctl_kind_multi_cluster.test.sh
  test/kwokctl/kwokctl_multi_cluster_test.sh
  test/kwokctl/kwokctl_nerdctl_multi_cluster.test.sh
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#258 Update docs for install
  site/content/en/docs/user/install.md
  site/content/en/docs/user/kwok-in-cluster.md
  site/content/en/docs/user/kwok-in-local.md
  site/content/en/docs/user/kwokctl-manage-cluster.md
  site/content/en/menu/index.md
Labels: approved, kind/documentation, cncf-cla: yes, size/M

#263 [kwokctl] Support port exposure for controller-port
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/v1alpha1/kwokctl_configuration_types.go
  pkg/config/vars.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/components/kwok_controller.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/kind.go
  pkg/kwokctl/runtime/kind/kind.yaml.tpl
  test/kwokctl/kwokctl_workable_test.sh
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#244 feat: detect runtime automatically
  .github/workflows/test.yaml
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/zz_generated.defaults.go
  pkg/config/vars.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/init.go
  pkg/kwokctl/runtime/config.go
  pkg/kwokctl/runtime/kind/cluster.go
  test/kwokctl/kwokctl-config-runtimes.yaml
  test/kwokctl/kwokctl_auto_detect.test.sh
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#275 Fix the deletion behavior
  pkg/kwok/controllers/finalizers.go
  pkg/kwok/controllers/finalizers_test.go
Labels: kind/bug, approved, cncf-cla: yes, size/M

#277 Fix default stages name
  pkg/kwok/controllers/lifecycle.go
  pkg/kwok/controllers/lifecycle_test.go
Labels: kind/bug, approved, cncf-cla: yes, size/M

#281 Automated cherry pick of #266: Update benchmark
  .github/workflows/releases.yaml
  .github/workflows/test.yaml
Labels: approved, size/S, cncf-cla: yes

#278 Automated cherry pick of #250: Fix pprof
  pkg/kwok/server/profiling.go
Labels: approved, size/S, cncf-cla: yes

#279 Automated cherry pick of #275: Avoid clearing empty finalizers
  pkg/kwok/controllers/finalizers.go
  pkg/kwok/controllers/finalizers_test.go
Labels: approved, cncf-cla: yes, size/M

#280 Automated cherry pick of #277: Fix default stages name
  pkg/kwok/controllers/lifecycle.go
  pkg/kwok/controllers/lifecycle_test.go
Labels: approved, cncf-cla: yes, size/M

#276 Uniform "not found" output
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/pod_controller.go
Labels: kind/bug, approved, kind/cleanup, cncf-cla: yes, size/M

#282 Automated cherry pick of #276: Uniform "not found" output
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/pod_controller.go
Labels: approved, cncf-cla: yes, size/M

#285 Cleanup load config
  pkg/config/config.go
  pkg/config/context.go
  pkg/config/context_test.go
  pkg/config/flags.go
  pkg/config/vars.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#267 Update docs for contributing
  README.md
  site/assets/_custom.scss
  site/assets/mermaid.json
  site/assets/mermaid_dark.json
  site/assets/plugins/_numbered.scss
  site/config.yaml
  site/content/en/_index.md
  site/content/en/docs/contributing/development.md
  site/content/en/docs/contributing/documentation.md
  site/content/en/docs/contributing/getting-started.md
  site/content/en/docs/design/introduction.md
  site/content/en/docs/user/stages-configuration.md
  site/content/en/menu/index.md
  site/layouts/shortcodes/ghlabel.html
  site/layouts/shortcodes/mermaid.html
Labels: approved, kind/documentation, cncf-cla: yes, size/L

#290 Update concurrency of test
  .github/workflows/test.yaml
Labels: approved, kind/cleanup, size/S, cncf-cla: yes

#293 Fix issue template
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes

#292 Add test for releases
  .github/workflows/test.yaml
  Makefile
  test/release/build.test.sh
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#296 Bump Hugo version
  netlify.toml
  site/Makefile
Labels: approved, kind/documentation, size/XS, cncf-cla: yes, lgtm

#297 Cherry pick of #294: Bump golang.org/x/net from 0.4.0 to 0.7.0
  go.mod
  go.sum
Labels: kind/bug, approved, size/S, cncf-cla: yes

#302 Revert "Bump Hugo version"
  netlify.toml
  site/Makefile
Labels: approved, size/XS, cncf-cla: yes, lgtm

#301 Add check for hugo version
  .github/workflows/test.yaml
  site/Makefile
Labels: approved, kind/cleanup, size/S, cncf-cla: yes

#295 refactor a cleanUp function
  pkg/kwokctl/cmd/create/cluster/cluster.go
Labels: ok-to-test, approved, kind/cleanup, size/S, cncf-cla: yes, lgtm

#305 check src exists and use abspath
  pkg/kwok/cmd/root.go
  pkg/utils/file/download.go
  pkg/utils/path/path.go
  pkg/utils/path/path_test.go
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#309 [doc] Fix edit path
  site/config.yaml
Labels: kind/bug, approved, kind/documentation, size/XS, cncf-cla: yes

#289 build: add builder args to support build with nerdctl
  .github/workflows/test.yaml
  Makefile
  images/cluster/build.sh
  images/kwok/build.sh
  test/kwokctl/helper.sh
  test/release/build.test.sh
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#310 [doc] Add adopters list
  site/content/en/docs/adopters/_index.md
  site/content/en/menu/index.md
  site/layouts/shortcodes/adopters.html
Labels: approved, kind/documentation, cncf-cla: yes, size/M

#312 Adopters: add clusterpedia
  site/assets/adopters/clusterpedia.yaml
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#313 [ci] Replace 'realpath --relative-to'
  images/cluster/build.sh
  images/kwok/build.sh
  test/release/build.test.sh
Labels: approved, kind/cleanup, cncf-cla: yes, size/M

#315 Remove TypeMeta in internalversion
  pkg/apis/internalversion/conversion.go
  pkg/apis/internalversion/kwok_configuration_types.go
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/stage_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/config/compatibility/compatibility.go
  pkg/config/config_test.go
Labels: approved, kind/cleanup, kind/api-change, cncf-cla: yes, size/L

#316 Add Multi-NIC CNI case to the list
  site/assets/adopters/multi-nic-cni.yaml
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#317 Fix typo
  pkg/apis/v1alpha1/kwokctl_configuration_types.go
  pkg/kwokctl/pki/pkiutil.go
Labels: ok-to-test, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm

#319 clean: Wrapping sync.Map with Generics
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/kwok/controllers/renderer.go
  pkg/kwok/controllers/utils.go
  pkg/utils/maps/doc.go
  pkg/utils/maps/sync.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#321 [doc] Update Slack channels
  site/content/en/docs/contributing/getting-started.md
Labels: approved, kind/documentation, size/XS, cncf-cla: yes

#318 log: change not managed pod log to debug, print delay as string
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/pod_controller.go
  pkg/log/logger.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#322 Bump requirements
  hack/requirements.sh
Labels: approved, kind/cleanup, size/S, cncf-cla: yes

#233 add port-forward logic with PortForward and ClusterPortForward type
  .github/workflows/test.yaml
  Makefile
  pkg/apis/internalversion/cluster_port_forward_types.go
  pkg/apis/internalversion/conversion.go
  pkg/apis/internalversion/object_selector.go
  pkg/apis/internalversion/object_selector_test.go
  pkg/apis/internalversion/port_forward_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/cluster_port_forward_types.go
  pkg/apis/v1alpha1/object_selector.go
  pkg/apis/v1alpha1/port_forward_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/config/config.go
  pkg/kwok/cmd/root.go
  pkg/kwok/server/debugging_port_forword.go
  pkg/kwok/server/portforward/httpstream.go
  pkg/kwok/server/portforward/websocket.go
  pkg/kwok/server/server.go
  pkg/utils/slices/slices.go
  test/kwokctl/fake-pod-in-other-ns.yaml
  test/kwokctl/kwokctl_binary_port_forward.test.sh
  test/kwokctl/kwokctl_docker_port_forward.test.sh
  test/kwokctl/kwokctl_kind_port_forward.test.sh
  test/kwokctl/kwokctl_nerdctl_port_forward.test.sh
  test/kwokctl/kwokctl_port_forward_test.sh
  test/kwokctl/port-forward.yaml
Labels: kind/feature, ok-to-test, size/XXL, approved, cncf-cla: yes, lgtm

#327 Fix flake for port forward
  pkg/kwokctl/runtime/kind/cluster.go
  test/kwokctl/kwokctl_port_forward_test.sh
Labels: approved, cncf-cla: yes, size/M, kind/flake

#326 Clean up exec
  pkg/kwok/server/debugging_port_forword.go
  pkg/kwokctl/cmd/etcdctl/etcdctl.go
  pkg/kwokctl/cmd/get/kubeconfig/kubeconfig.go
  pkg/kwokctl/cmd/kubectl/kubectl.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/binary/cluster_snapshot.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/cluster_snapshot.go
  pkg/kwokctl/runtime/config.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/cluster_snapshot.go
  pkg/utils/exec/cmd.go
  pkg/utils/exec/exec.go
  pkg/utils/image/pull.go
  pkg/utils/version/version.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/L

#330 cleanup: add ut for kwok
  pkg/kwok/controllers/utils_test.go
  pkg/utils/envs/envs_test.go
  pkg/utils/maps/sync_test.go
  pkg/utils/slices/slices_test.go
Labels: ok-to-test, size/XL, approved, kind/cleanup, cncf-cla: yes, lgtm

#331 Back buildx to 0.9.1
  hack/requirements.sh
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes
