Repository kubernetes-sigs/kwok, pull requests merged in 2023-12, with the labels that each got.

#828 Refactor pod builder for kind
  pkg/kwokctl/components/dashboard.go
  pkg/kwokctl/components/etcd.go
  pkg/kwokctl/components/jaeger.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/components/kube_controller_manager.go
  pkg/kwokctl/components/kube_scheduler.go
  pkg/kwokctl/components/kwok_controller.go
  pkg/kwokctl/components/pods.go
  pkg/kwokctl/components/pods_test.go
  pkg/kwokctl/components/prometheus.go
  pkg/kwokctl/components/utils.go
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/dashboard_deployment.go
  pkg/kwokctl/runtime/kind/dashboard_deployment.yaml.tpl
  pkg/kwokctl/runtime/kind/jaeger_deployment.go
  pkg/kwokctl/runtime/kind/jaeger_deployment.yaml.tpl
  pkg/kwokctl/runtime/kind/kind.go
  pkg/kwokctl/runtime/kind/kind.yaml.tpl
  pkg/kwokctl/runtime/kind/kwok_controller_pod.go
  pkg/kwokctl/runtime/kind/kwok_controller_pod.yaml.tpl
  pkg/kwokctl/runtime/kind/prometheus.go
  pkg/kwokctl/runtime/kind/prometheus.yaml.tpl
  pkg/kwokctl/runtime/kind/prometheus_deployment.go
  pkg/kwokctl/runtime/kind/prometheus_deployment.yaml.tpl
  test/kwokctl/kwokctl_metric_test.sh
  test/kwokctl/testdata/binary/create_cluster.txt
  test/kwokctl/testdata/binary/create_cluster_with_extra.txt
  test/kwokctl/testdata/binary/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/binary/start_cluster.txt
  test/kwokctl/testdata/docker/create_cluster.txt
  test/kwokctl/testdata/docker/create_cluster_with_extra.txt
  test/kwokctl/testdata/docker/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind-podman/create_cluster.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind/create_cluster.txt
  test/kwokctl/testdata/kind/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/nerdctl/create_cluster.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_extra.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/podman/create_cluster.txt
  test/kwokctl/testdata/podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/podman/create_cluster_with_verbosity.txt
Labels: size/XXL, approved, kind/cleanup, cncf-cla: yes, release-note-none

#860 Fix e2e flake
  test/e2e/helper/build.go
  test/e2e/helper/kustomize.go
  test/e2e/helper/utils.go
Labels: approved, size/S, cncf-cla: yes, kind/flake, release-note-none

#857 [kwokctl] Shorten the default node lease
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/kwok/controllers/node_lease_controller.go
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/runtime/binary/cluster_snapshot.go
  pkg/kwokctl/runtime/compose/cluster_snapshot.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/cluster_snapshot.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
  test/e2e/helper/node.go
  test/e2e/kwokctl/binary/kubectl_test.go
  test/e2e/kwokctl/docker/kubectl_test.go
  test/e2e/kwokctl/kind-podman/kubectl_test.go
  test/e2e/kwokctl/kind/kubectl_test.go
  test/e2e/kwokctl/nerdctl/kubectl_test.go
  test/e2e/kwokctl/podman/kubectl_test.go
  test/e2e/restart.go
  test/e2e/snapshot.go
  test/kwokctl/testdata/binary/create_cluster.txt
  test/kwokctl/testdata/binary/create_cluster_with_extra.txt
  test/kwokctl/testdata/binary/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/binary/snapshot_restore_etcd.txt
  test/kwokctl/testdata/binary/start_cluster.txt
  test/kwokctl/testdata/docker/create_cluster.txt
  test/kwokctl/testdata/docker/create_cluster_with_extra.txt
  test/kwokctl/testdata/docker/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/docker/snapshot_restore_etcd.txt
  test/kwokctl/testdata/kind-podman/snapshot_restore_etcd.txt
  test/kwokctl/testdata/kind/snapshot_restore_etcd.txt
  test/kwokctl/testdata/nerdctl/create_cluster.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_extra.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/nerdctl/snapshot_restore_etcd.txt
  test/kwokctl/testdata/podman/create_cluster.txt
  test/kwokctl/testdata/podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/podman/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/podman/snapshot_restore_etcd.txt
Labels: kind/bug, kind/feature, size/XL, approved, kind/documentation, kind/api-change, cncf-cla: yes, release-note

#862 Clean up kwok controller
  pkg/kwok/cmd/root.go
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/controller_test.go
Labels: size/XL, approved, kind/cleanup, cncf-cla: yes, release-note-none

#863 Clean up snapshot yaml configuration
  pkg/kwokctl/cmd/snapshot/export/export.go
  pkg/kwokctl/cmd/snapshot/restore/restore.go
  pkg/kwokctl/cmd/snapshot/save/save.go
  pkg/kwokctl/runtime/binary/cluster_snapshot.go
  pkg/kwokctl/runtime/cluster.go
  pkg/kwokctl/runtime/cluster_snapshot.go
  pkg/kwokctl/runtime/compose/cluster_snapshot.go
  pkg/kwokctl/runtime/config.go
  pkg/kwokctl/runtime/kind/cluster_snapshot.go
  pkg/kwokctl/scale/scale.go
  pkg/kwokctl/snapshot/load.go
  pkg/kwokctl/snapshot/save.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/M, release-note-none

#853 [kwokctl] Add metrics for components
  pkg/apis/config/v1alpha1/kwokctl_configuration_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/internalversion/kwokctl_configuration_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/kwokctl/components/etcd.go
  pkg/kwokctl/components/kube_apiserver.go
  pkg/kwokctl/components/kube_controller_manager.go
  pkg/kwokctl/components/kube_scheduler.go
  pkg/kwokctl/components/kwok_controller.go
  pkg/kwokctl/components/prometheus.go
  pkg/kwokctl/components/prometheus_config.go
  pkg/kwokctl/components/prometheus_config.yaml.tpl
  pkg/kwokctl/runtime/binary/cluster.go
  pkg/kwokctl/runtime/binary/prometheus.yaml.tpl
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/compose/prometheus.go
  pkg/kwokctl/runtime/compose/prometheus.yaml.tpl
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/prometheus.go
  pkg/kwokctl/runtime/kind/prometheus.yaml.tpl
  site/content/en/docs/generated/apis.md
  test/kwokctl/testdata/binary/create_cluster_with_extra.txt
  test/kwokctl/testdata/binary/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/docker/create_cluster_with_extra.txt
  test/kwokctl/testdata/docker/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_extra.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/podman/create_cluster_with_verbosity.txt
Labels: size/XXL, approved, kind/documentation, kind/api-change, cncf-cla: yes, release-note

#870 chore: add unit test for utils/queue package
  pkg/utils/queue/delaying_queue_test.go
  pkg/utils/queue/queue_test.go
Labels: ok-to-test, tide/merge-method-squash, approved, kind/cleanup, cncf-cla: yes, lgtm, release-note-none, size/L

#877 Fix extended key usage for kwokctl
  pkg/kwokctl/pki/pki.go
Labels: kind/bug, ok-to-test, tide/merge-method-squash, approved, size/S, cncf-cla: yes, lgtm, release-note-none

#871 chore(doc): add node lease controller description in architecture page
  site/content/en/docs/design/architecture.md
Labels: ok-to-test, tide/merge-method-squash, approved, size/S, kind/documentation, cncf-cla: yes, lgtm, release-note-none

#879 fix(kwokctl): modify misunderstanding description in config subcommand
  pkg/kwokctl/cmd/config/tidy/tidy.go
  pkg/kwokctl/cmd/config/view/view.go
  site/content/en/docs/generated/kwokctl_config.md
  site/content/en/docs/generated/kwokctl_config_tidy.md
  site/content/en/docs/generated/kwokctl_config_view.md
Labels: ok-to-test, tide/merge-method-squash, approved, kind/cleanup, size/S, kind/documentation, cncf-cla: yes, lgtm, release-note-none

#882 chore(doc): add weight description for Stage page
  kustomize/crd/bases/kwok.x-k8s.io_stages.yaml
  pkg/apis/internalversion/stage_types.go
  pkg/apis/v1alpha1/stage_types.go
  site/content/en/docs/generated/apis.md
  site/content/en/docs/user/stages-configuration.md
Labels: ok-to-test, tide/merge-method-squash, approved, size/S, kind/documentation, kind/api-change, cncf-cla: yes, lgtm, release-note-none

#886 Fix always renew lease when disconnection from apiserver
  pkg/kwok/controllers/node_lease_controller.go
Labels: kind/bug, approved, size/XS, cncf-cla: yes, release-note

#887 Clean up inspect component for Kind
  pkg/kwokctl/runtime/kind/cluster.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/M, release-note-none

#889 Fix flake unit test
  pkg/kwok/controllers/node_lease_controller_test.go
Labels: approved, size/S, cncf-cla: yes, kind/flake, release-note-none

#895 Add labels for PR create by dependabot
  .github/dependabot.yml
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes, release-note-none

#896 Fix bump releases
  .github/workflows/bump_releases.yaml
Labels: kind/bug, approved, kind/cleanup, size/XS, cncf-cla: yes, release-note-none

#883 chore(doc): add immediateNextStage description
  site/content/en/docs/user/stages-configuration.md
Labels: ok-to-test, tide/merge-method-squash, approved, kind/documentation, cncf-cla: yes, lgtm, size/M, release-note-none
