Repository kubernetes-sigs/kwok, pull requests merged in 2024-04, with the labels that each got.

#893 [doc] Add WinGet installation method
  site/content/en/docs/user/installation.md
Labels: approved, lifecycle/stale, size/S, kind/documentation, cncf-cla: yes, release-note-none

#991 Refactor CEL
  pkg/kwok/metrics/cel/evaluate.go
  pkg/kwok/metrics/evaluator.go
  pkg/kwok/metrics/evaluator_test.go
  pkg/kwok/metrics/metrics.go
  pkg/kwok/server/metrics.go
  pkg/kwok/server/metrics_resource_usage.go
  pkg/kwok/server/server.go
  pkg/utils/cel/default.go
  pkg/utils/cel/doc.go
  pkg/utils/cel/environment.go
  pkg/utils/cel/funcs.go
  pkg/utils/cel/quantity.go
  pkg/utils/cel/resource_list.go
Labels: size/XXL, approved, kind/cleanup, cncf-cla: yes, release-note-none

#1010 Remove old stages config
  stages/README.md
  stages/embed.go
  stages/kustomization.yaml
  stages/node-fast.yaml
  stages/node-heartbeat.yaml
  stages/pod-fast.yaml
  stages/pod-general.yaml
  test/kwok-with-cni/kwok-with-cni.test.sh
  test/kwok/kwok.test.sh
Labels: size/XL, approved, kind/cleanup, cncf-cla: yes, release-note-none

#1014 [kwokctl] Refactor download and progress bar
  go.mod
  go.sum
  pkg/kwokctl/cmd/create/cluster/cluster.go
  pkg/kwokctl/runtime/compose/cluster.go
  pkg/kwokctl/runtime/exec.go
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/utils/exec/pull.go
  pkg/utils/file/download.go
  pkg/utils/file/progress_bar.go
  pkg/utils/image/doc.go
  pkg/utils/image/pull.go
  pkg/utils/progressbar/doc.go
  pkg/utils/progressbar/format.go
  pkg/utils/progressbar/progressbar.go
  pkg/utils/progressbar/reader.go
  pkg/utils/width/doc.go
  pkg/utils/width/width.go
  pkg/utils/width/width_test.go
Labels: kind/feature, size/XL, approved, kind/cleanup, cncf-cla: yes, release-note

#1001 Support Sidecar container
  kustomize/stage/pod/fast/pod-ready.yaml
  test/e2e/helper/pod.go
Labels: kind/feature, approved, cncf-cla: yes, release-note, size/M

#1021 Structured Kind configuration
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/config/kind/v1alpha4/types.go
  pkg/kwokctl/runtime/kind/config/kubeadm/v1beta3/types.go
  pkg/kwokctl/runtime/kind/kind.go
  pkg/kwokctl/runtime/kind/kind.yaml.tpl
  test/kwokctl/testdata/docker/create_cluster_with_extra.txt
  test/kwokctl/testdata/extra.yaml
  test/kwokctl/testdata/kind-podman/create_cluster.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind/create_cluster.txt
  test/kwokctl/testdata/kind/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_extra.txt
  test/kwokctl/testdata/podman/create_cluster_with_extra.txt
Labels: kind/bug, kind/feature, size/XXL, approved, kind/cleanup, cncf-cla: yes, release-note

#1022 Add yaml formatter
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/failing-test.yaml
  .github/dependabot.yml
  .github/workflows/bump_releases.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/releases.yaml
  .github/workflows/test-site.yaml
  .github/workflows/test.yaml
  .golangci.yaml
  .yamlfmt.yaml
  cloudbuild.yaml
  hack/update-all.sh
  hack/update-yaml-format.sh
  hack/verify-all.sh
  hack/verify-yaml-format.sh
  kustomize/kwok/deployment.yaml
  site/assets/adopters/clusterpedia.yaml
  site/assets/adopters/daocloud.yaml
  site/assets/adopters/headlamp.yaml
  site/assets/adopters/multi-nic-cni.yaml
  site/config.yaml
  site/content/en/docs/adopters/_index.md
  test/kwok-with-cni/fake-deployment.yaml
  test/kwok-with-cni/fake-node.yaml
  test/kwok/fake-deployment.yaml
  test/kwok/fake-node.yaml
  test/kwokctl/fake-deployment.yaml
  test/kwokctl/kustomization.yaml
  test/kwokctl/testdata/extra.yaml
  test/lifecycle/fake-pod-stages.yaml
Labels: size/XXL, approved, kind/cleanup, kind/documentation, cncf-cla: yes, release-note-none

#1024 Promote podman to the second runtime for all
  pkg/config/vars.go
Labels: kind/feature, approved, size/XS, cncf-cla: yes, release-note

#1025 Promote binary runtime for all
  .github/workflows/test.yaml
  pkg/config/vars.go
  pkg/consts/consts.go
Labels: kind/feature, approved, cncf-cla: yes, release-note, size/M

#1026 Fix progress bar and cleanup
  pkg/log/logger_ctl.go
  pkg/utils/monospace/doc.go
  pkg/utils/monospace/monospace.go
  pkg/utils/monospace/monospace_test.go
  pkg/utils/progressbar/format.go
  pkg/utils/progressbar/format_test.go
Labels: kind/bug, approved, kind/cleanup, cncf-cla: yes, release-note-none, size/L

#1028 Check download file length and print download error message
  pkg/utils/file/download.go
  pkg/utils/image/pull.go
Labels: kind/bug, approved, cncf-cla: yes, size/M, release-note-none

#1019 Add a pod stage for failing an initContainer
  kustomize/stage/pod/chaos/pod-init-container-running-failed.yaml
Labels: kind/feature, tide/merge-method-squash, approved, cncf-cla: yes, release-note, lgtm, size/M

#1033 Add a pod stage for failing a container
  kustomize/stage/pod/chaos/pod-container-running-failed.yaml
Labels: kind/feature, approved, cncf-cla: yes, release-note, lgtm, size/M

#1037 Support configurable delay durations in pod stages
  kustomize/stage/pod/general/pod-complete.yaml
  kustomize/stage/pod/general/pod-create.yaml
  kustomize/stage/pod/general/pod-delete.yaml
  kustomize/stage/pod/general/pod-init-container-completed.yaml
  kustomize/stage/pod/general/pod-init-container-running.yaml
  kustomize/stage/pod/general/pod-ready.yaml
  kustomize/stage/pod/general/pod-remove-finalizer.yaml
Labels: kind/feature, approved, size/S, cncf-cla: yes, release-note, lgtm

#1039 [doc] Fix broken link and update navigation
  site/content/en/docs/user/_index.md
  site/content/en/docs/user/stages-configuration.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, release-note-none

#1043 Fix typo
  pkg/kwokctl/runtime/kind/config/kubeadm/v1beta3/types.go
  pkg/kwokctl/runtime/kind/kind.go
Labels: approved, kind/cleanup, size/S, cncf-cla: yes, release-note-none

#984 Add patches to instead of statusTemplate in Stage
  kustomize/crd/bases/kwok.x-k8s.io_stages.yaml
  pkg/apis/internalversion/conversion.go
  pkg/apis/internalversion/stage_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/stage_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/stage_controller.go
  pkg/kwok/controllers/stage_controller_test.go
  pkg/kwok/controllers/utils.go
  site/content/en/docs/generated/apis.md
Labels: kind/feature, size/XL, approved, kind/documentation, kind/api-change, cncf-cla: yes, release-note

#1042 [release-0.5] Structured Kind configuration
  pkg/kwokctl/runtime/kind/cluster.go
  pkg/kwokctl/runtime/kind/config/kind/v1alpha4/types.go
  pkg/kwokctl/runtime/kind/config/kubeadm/v1beta3/types.go
  pkg/kwokctl/runtime/kind/kind.go
  pkg/kwokctl/runtime/kind/kind.yaml.tpl
  test/kwokctl/testdata/docker/create_cluster_with_extra.txt
  test/kwokctl/testdata/extra.yaml
  test/kwokctl/testdata/kind-podman/create_cluster.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind/create_cluster.txt
  test/kwokctl/testdata/kind/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_extra.txt
  test/kwokctl/testdata/podman/create_cluster_with_extra.txt
Labels: size/XXL, approved, cncf-cla: yes, release-note

#1048 Release v0.5.2
  pkg/consts/consts.go
  test/kwokctl/testdata/binary/create_cluster.txt
  test/kwokctl/testdata/binary/create_cluster_with_extra.txt
  test/kwokctl/testdata/binary/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/docker/create_cluster.txt
  test/kwokctl/testdata/docker/create_cluster_with_extra.txt
  test/kwokctl/testdata/docker/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind-podman/create_cluster.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind/create_cluster.txt
  test/kwokctl/testdata/kind/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/nerdctl/create_cluster.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_extra.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/podman/create_cluster.txt
  test/kwokctl/testdata/podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/podman/create_cluster_with_verbosity.txt
Labels: approved, kind/cleanup, release-note-none, size/L

#1046 Fix nil pointer error in chaos stages
  kustomize/stage/pod/chaos/pod-container-running-failed.yaml
  kustomize/stage/pod/chaos/pod-init-container-running-failed.yaml
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm, release-note-none

#1050 Fix typos in Makefile
  Makefile
Labels: kind/bug, approved, size/XS, cncf-cla: yes, release-note, lgtm

#1055 Refactor the demo script to democtl.sh
  .xresources
  Makefile
  demo/.gitignore
  demo/Makefile
  demo/README.md
  demo/play-demo.sh
  hack/democtl.sh
Labels: kind/feature, size/XL, approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm, release-note-none

#1054 Add yuanchen8911 as a reviewer
  OWNERS
Labels: approved, size/XS, cncf-cla: yes, lgtm, release-note-none
