Repository kubernetes-sigs/kwok, pull requests merged in 2024-05, with the labels that each got.

#1056 Fix a bug in democtl.sh
  hack/democtl.sh
Labels: kind/bug, approved, size/XS, cncf-cla: yes, lgtm, release-note-none

#1059 fix: hack/democtl.sh: Avoid TREM being overwritten
  hack/democtl.sh
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm, release-note-none

#1061 fix: democtl.sh: install asciinema
  hack/democtl.sh
Labels: kind/bug, approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm, release-note-none

#1017 Support patch type in Stage
  go.mod
  go.sum
  kustomize/crd/bases/kwok.x-k8s.io_stages.yaml
  pkg/apis/internalversion/stage_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/stage_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/stage_controller.go
  pkg/kwok/controllers/utils.go
  site/content/en/docs/generated/apis.md
  test/e2e/helper/node.go
  test/e2e/helper/pod.go
  test/e2e/jsonpatch.go
  test/e2e/jsonpatch.yaml
  test/e2e/kwok/default/kwok_test.go
Labels: size/XL, approved, kind/documentation, kind/api-change, cncf-cla: yes, release-note

#1066 Add builtin WORK_DIR variables for make %.cast
  Makefile
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes, lgtm, release-note-none

#1058 Add an in-cluster example for error injection
  site/content/en/docs/user/examples/injectfailure/failed-pod.yaml
  site/content/en/docs/user/examples/injectfailure/init-container-error-injection.cast
  site/content/en/docs/user/examples/injectfailure/init-container-error-injection.demo
  site/content/en/docs/user/examples/injectfailure/init-container-error-injection.svg
  site/content/en/docs/user/examples/injectfailure/virtual-gpu-node.yaml
Labels: kind/feature, size/XXL, approved, kind/documentation, cncf-cla: yes, lgtm, release-note-none

#1057 Add a demo for injecting error to a container
  demo/container-failure.demo
  demo/container-failure.svg
Labels: kind/feature, approved, size/S, kind/documentation, cncf-cla: yes, lgtm, release-note-none

#1067 Refactor Stage implementation
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/kwok/controllers/stage_controller.go
  pkg/kwok/controllers/stage_controller_test.go
  pkg/kwok/controllers/stages_manager.go
  pkg/kwok/controllers/utils.go
  pkg/utils/lifecycle/doc.go
  pkg/utils/lifecycle/finalizers.go
  pkg/utils/lifecycle/finalizers_test.go
  pkg/utils/lifecycle/lifecycle.go
  pkg/utils/lifecycle/next.go
Labels: size/XL, approved, kind/cleanup, cncf-cla: yes, lgtm, release-note-none

#1069 Add NVIDIA/Knavigator to adopters
  site/assets/adopters/knavigator.yaml
Labels: approved, kind/documentation, size/XS, cncf-cla: yes, lgtm, release-note-none

#1071 Clarify CRD and CR Acronyms
  site/content/en/docs/user/kwok-in-cluster.md
Labels: ok-to-test, approved, kind/documentation, size/XS, cncf-cla: yes, lgtm, release-note-none

#1072 Correct warning message grammar in the error handling block.
  pkg/kwokctl/cmd/delete/cluster/cluster.go
  pkg/kwokctl/cmd/export/logs/logs.go
  pkg/kwokctl/cmd/get/components/components.go
  pkg/kwokctl/cmd/get/kubeconfig/kubeconfig.go
  pkg/kwokctl/cmd/kubectl/kubectl.go
  pkg/kwokctl/cmd/logs/logs.go
  pkg/kwokctl/cmd/scale/scale.go
  pkg/kwokctl/cmd/snapshot/record/record.go
  pkg/kwokctl/cmd/snapshot/replay/replay.go
  pkg/kwokctl/cmd/snapshot/restore/restore.go
  pkg/kwokctl/cmd/snapshot/save/save.go
  pkg/kwokctl/cmd/start/cluster/cluster.go
  pkg/kwokctl/cmd/stop/cluster/cluster.go
Labels: ok-to-test, approved, kind/cleanup, size/S, cncf-cla: yes, release-note, lgtm

#1068 Add test for stages
  hack/test_stage/main.go
  hack/update-all.sh
  hack/update-stages.sh
  hack/verify-all.sh
  hack/verify-stages.sh
  kustomize/stage/node/fast/testdata/node-pending.input.yaml
  kustomize/stage/node/fast/testdata/node-pending.output.yaml
  kustomize/stage/pod/fast/testdata/pod-pending.input.yaml
  kustomize/stage/pod/fast/testdata/pod-pending.output.yaml
  kustomize/stage/pod/fast/testdata/pod-running-with-job.input.yaml
  kustomize/stage/pod/fast/testdata/pod-running-with-job.output.yaml
  kustomize/stage/pod/fast/testdata/pod-terminating.input.yaml
  kustomize/stage/pod/fast/testdata/pod-terminating.output.yaml
  pkg/config/config.go
  pkg/kwok/controllers/controller.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/node_controller_test.go
  pkg/kwok/controllers/pod_controller_test.go
  pkg/kwok/controllers/stage_controller_test.go
  pkg/tools/stage/stage.go
  pkg/utils/gotpl/funcs.go
  pkg/utils/gotpl/renderer.go
  pkg/utils/lifecycle/lifecycle.go
  pkg/utils/yaml/encoder.go
Labels: kind/feature, size/XL, approved, kind/documentation, cncf-cla: yes, release-note-none

#1079 Update Prometheus Data Source Docs for Grafana
  site/content/en/docs/examples/prometheus.md
Labels: ok-to-test, approved, kind/documentation, size/XS, cncf-cla: yes, lgtm, release-note-none

#1075 Fix node info not filling
  kustomize/stage/node/fast/node-initialize.yaml
  kustomize/stage/node/fast/testdata/node-pending.output.yaml
Labels: kind/bug, approved, cncf-cla: yes, release-note, size/M

#1081 Bump k8s releases and remove automation
  .github/workflows/bump_releases.yaml
  hack/supported_releases.sh
  pkg/kwokctl/k8s/feature_gates_data.go
  supported_releases.txt
  test/release/testdata/build-with-push-bucket-staging.txt
  test/release/testdata/build-with-push-bucket.txt
  test/release/testdata/build-with-push-ghrelease.txt
  test/release/testdata/build.txt
  test/release/testdata/cluster-image-nerdctl-with-push-staging.txt
  test/release/testdata/cluster-image-nerdctl-with-push.txt
  test/release/testdata/cluster-image-nerdctl.txt
  test/release/testdata/cluster-image-podman-with-push-staging.txt
  test/release/testdata/cluster-image-podman-with-push.txt
  test/release/testdata/cluster-image-podman.txt
  test/release/testdata/cluster-image-with-push-staging.txt
  test/release/testdata/cluster-image-with-push.txt
  test/release/testdata/cluster-image.txt
  test/release/testdata/cross-build-with-push-bucket-staging.txt
  test/release/testdata/cross-build-with-push-bucket.txt
  test/release/testdata/cross-build-with-push-ghrelease.txt
  test/release/testdata/cross-build.txt
  test/release/testdata/cross-cluster-image-nerdctl-with-push-staging.txt
  test/release/testdata/cross-cluster-image-nerdctl-with-push.txt
  test/release/testdata/cross-cluster-image-nerdctl.txt
  test/release/testdata/cross-cluster-image-podman-with-push-staging.txt
  test/release/testdata/cross-cluster-image-podman-with-push.txt
  test/release/testdata/cross-cluster-image-podman.txt
  test/release/testdata/cross-cluster-image-with-push-staging.txt
  test/release/testdata/cross-cluster-image-with-push.txt
  test/release/testdata/cross-cluster-image.txt
Labels: size/XL, approved, kind/cleanup, cncf-cla: yes, release-note-none

#1084 Add Test Cases for slices package
  pkg/utils/slices/slices_test.go
Labels: ok-to-test, tide/merge-method-squash, approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1094 Update Test Cases for Tail package.
  pkg/utils/tail/tail_test.go
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#1098 Bump go to 1.22
  .github/workflows/golangci-lint.yaml
  .github/workflows/releases.yaml
  .github/workflows/test.yaml
  .golangci.yaml
  go.mod
  hack/requirements.sh
Labels: approved, kind/cleanup, size/S, cncf-cla: yes, release-note-none

#1101 Adding sets_test.go
  pkg/utils/sets/sets_test.go
Labels: ok-to-test, tide/merge-method-squash, approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1091 Added Tests for the Monospace package.
  pkg/utils/monospace/monospace_test.go
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#1093 Added Tests for Printer package.
  pkg/utils/printers/table_printer_test.go
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#1103 Fix kwokctl compatibility
  pkg/apis/internalversion/conversion.go
  pkg/apis/internalversion/zz_generated.conversion.go
Labels: kind/bug, approved, kind/api-change, cncf-cla: yes, size/M, release-note-none

#1102 Bump k8s to 1.30
  go.mod
  go.sum
  hack/update-codegen.sh
  kustomize/crd/bases/kwok.x-k8s.io_attaches.yaml
  kustomize/crd/bases/kwok.x-k8s.io_clusterattaches.yaml
  kustomize/crd/bases/kwok.x-k8s.io_clusterexecs.yaml
  kustomize/crd/bases/kwok.x-k8s.io_clusterlogs.yaml
  kustomize/crd/bases/kwok.x-k8s.io_clusterportforwards.yaml
  kustomize/crd/bases/kwok.x-k8s.io_clusterresourceusages.yaml
  kustomize/crd/bases/kwok.x-k8s.io_execs.yaml
  kustomize/crd/bases/kwok.x-k8s.io_logs.yaml
  kustomize/crd/bases/kwok.x-k8s.io_metrics.yaml
  kustomize/crd/bases/kwok.x-k8s.io_portforwards.yaml
  kustomize/crd/bases/kwok.x-k8s.io_resourceusages.yaml
  kustomize/crd/bases/kwok.x-k8s.io_stages.yaml
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/apis/v1alpha1/zz_generated.defaults.go
  pkg/consts/consts.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
  test/kwokctl/testdata/binary/create_cluster.txt
  test/kwokctl/testdata/binary/create_cluster_with_extra.txt
  test/kwokctl/testdata/binary/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/docker/create_cluster.txt
  test/kwokctl/testdata/docker/create_cluster_with_extra.txt
  test/kwokctl/testdata/docker/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind-podman/create_cluster.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind-podman/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/kind/create_cluster.txt
  test/kwokctl/testdata/kind/create_cluster_with_extra.txt
  test/kwokctl/testdata/kind/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/nerdctl/create_cluster.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_extra.txt
  test/kwokctl/testdata/nerdctl/create_cluster_with_verbosity.txt
  test/kwokctl/testdata/podman/create_cluster.txt
  test/kwokctl/testdata/podman/create_cluster_with_extra.txt
  test/kwokctl/testdata/podman/create_cluster_with_verbosity.txt
Labels: approved, kind/cleanup, kind/documentation, kind/api-change, cncf-cla: yes, release-note-none, size/L

#1108 Fix the expressionFrom to get nil
  pkg/utils/expression/query.go
  pkg/utils/expression/query_test.go
Labels: kind/bug, approved, cncf-cla: yes, release-note, size/M

#1107 adding dryrun_test.go
  pkg/kwokctl/dryrun/dryrun_test.go
Labels: ok-to-test, approved, cncf-cla: yes, release-note, lgtm, size/M

#1111 Correct Grammar
  site/content/en/docs/user/stages-configuration.md
Labels: ok-to-test, approved, kind/documentation, size/XS, cncf-cla: yes, lgtm, release-note-none

#1121 Bump golangci-lint to v1.58.2
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
  hack/update-go-lint.sh
  hack/verify-go-lint.sh
Labels: ok-to-test, approved, kind/cleanup, size/S, cncf-cla: yes, lgtm, release-note-none

#1090 Adding tests : maps_test.go
  pkg/utils/maps/maps_test.go
Labels: ok-to-test, tide/merge-method-squash, approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1106 Add Tests for Signal package.
  pkg/utils/signals/signals_test.go
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#1116 adding tests for package k8s
  pkg/kwokctl/k8s/etcd_test.go
  pkg/kwokctl/k8s/feature_gates_test.go
  pkg/kwokctl/k8s/kube_apiserver_tracing_config_test.go
  pkg/kwokctl/k8s/runtime_config_test.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, release-note-none, size/L
