Repository kubernetes-sigs/kwok, pull requests merged in 2024-06, with the labels that each got.

#1114 Added unit tests for Gauge and counter metrics
  pkg/kwok/metrics/counter.go
  pkg/kwok/metrics/counter_test.go
  pkg/kwok/metrics/gauge_test.go
Labels: kind/feature, ok-to-test, tide/merge-method-squash, approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1125 [kwokctl] Added --all flag to kwokctl delete cluster command
  pkg/kwokctl/cmd/delete/cluster/cluster.go
  site/content/en/docs/generated/kwokctl_delete_cluster.md
Labels: kind/feature, ok-to-test, tide/merge-method-squash, approved, kind/documentation, cncf-cla: yes, release-note, lgtm, size/M

#1137 Fix jitter delay on invalid argument
  pkg/utils/lifecycle/lifecycle.go
Labels: kind/bug, approved, size/XS, cncf-cla: yes, release-note

#1128 [kwokctl] Support Force Delete Cluster
  pkg/kwokctl/cmd/delete/cluster/cluster.go
  site/content/en/docs/generated/kwokctl_delete_cluster.md
Labels: kind/feature, ok-to-test, approved, size/S, kind/documentation, cncf-cla: yes, release-note, lgtm

#1142 Fix component duplication when create twice
  pkg/kwokctl/cmd/create/cluster/cluster.go
Labels: kind/bug, approved, cncf-cla: yes, release-note, size/M

#1143 Add verify dependencies version to CI
  .dependencies.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/releases.yaml
  .github/workflows/test.yaml
  hack/requirements.sh
  hack/verify-all.sh
  hack/verify-dependencies-version.sh
Labels: approved, kind/cleanup, cncf-cla: yes, release-note-none, size/L

#1141 Bump themes and hugo
  netlify.toml
  site/Makefile
  site/config.yaml
  site/go.mod
  site/go.sum
Labels: approved, kind/cleanup, size/S, kind/documentation, cncf-cla: yes, release-note-none

#1145 [doc] Add shortcode `code-sample`
  site/layouts/shortcodes/code-sample.html
Labels: kind/feature, approved, size/S, kind/documentation, cncf-cla: yes, release-note-none
