Repository kubernetes-sigs/kwok, pull requests merged in 2025-05, with the labels that each got.

#1363 Support CEL for Stage
  kustomize/crd/bases/kwok.x-k8s.io_stages.yaml
  pkg/apis/internalversion/cel_types.go
  pkg/apis/internalversion/conversion.go
  pkg/apis/internalversion/jq_types.go
  pkg/apis/internalversion/stage_types.go
  pkg/apis/internalversion/zz_generated.conversion.go
  pkg/apis/internalversion/zz_generated.deepcopy.go
  pkg/apis/v1alpha1/cel_types.go
  pkg/apis/v1alpha1/jq_types.go
  pkg/apis/v1alpha1/stage_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/kwok/controllers/node_controller.go
  pkg/kwok/controllers/pod_controller.go
  pkg/kwok/controllers/stage_controller.go
  pkg/kwok/controllers/stage_controller_test.go
  pkg/kwok/controllers/stages_manager.go
  pkg/tools/stage/stage.go
  pkg/utils/cel/environment.go
  pkg/utils/expression/value_duration_from.go
  pkg/utils/expression/value_duration_from_test.go
  pkg/utils/expression/value_int_from.go
  pkg/utils/expression/value_int_from_test.go
  pkg/utils/lifecycle/lifecycle.go
  pkg/utils/lifecycle/value_duration_from.go
  pkg/utils/lifecycle/value_duration_from_test.go
  pkg/utils/lifecycle/value_int_from.go
  pkg/utils/lifecycle/value_int_from_test.go
  site/content/en/docs/generated/apis.md
Labels: kind/feature, size/XXL, approved, kind/documentation, kind/api-change, cncf-cla: yes, release-note

#1365 docs: add providerID to node configuration and update docs
  site/config.yaml
  site/content/en/docs/user/known-issues/nodes-unexpectedly-deleted.md
Labels: ok-to-test, approved, kind/documentation, cncf-cla: yes, lgtm, size/M, release-note-none

#1370 Bump etcd
  go.mod
  go.sum
  pkg/kwokctl/k8s/etcd.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
  test/e2e/kwokctl/dryrun/testdata/binary/create_cluster.txt
  test/e2e/kwokctl/dryrun/testdata/binary/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/binary/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/binary/snapshot_restore_etcd.txt
  test/e2e/kwokctl/dryrun/testdata/binary/snapshot_save_etcd.txt
  test/e2e/kwokctl/dryrun/testdata/docker/create_cluster.txt
  test/e2e/kwokctl/dryrun/testdata/docker/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/docker/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/docker/snapshot_restore_etcd.txt
  test/e2e/kwokctl/dryrun/testdata/kind-podman/snapshot_restore_etcd.txt
  test/e2e/kwokctl/dryrun/testdata/kind/snapshot_restore_etcd.txt
  test/e2e/kwokctl/dryrun/testdata/nerdctl/create_cluster.txt
  test/e2e/kwokctl/dryrun/testdata/nerdctl/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/nerdctl/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/nerdctl/snapshot_restore_etcd.txt
  test/e2e/kwokctl/dryrun/testdata/podman/create_cluster.txt
  test/e2e/kwokctl/dryrun/testdata/podman/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/podman/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/podman/snapshot_restore_etcd.txt
Labels: approved, kind/cleanup, kind/documentation, cncf-cla: yes, size/M, release-note-none

#1373 Add the http response header 'Server'
  pkg/kwok/server/server.go
  pkg/utils/version/vars.go
Labels: kind/feature, approved, size/S, cncf-cla: yes, release-note

#1364 Bump k8s to v1.33
  .dependencies.yaml
  go.mod
  go.sum
  hack/requirements.sh
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/apis_client.go
  pkg/consts/consts.go
  pkg/kwokctl/etcd/scheme.go
  pkg/kwokctl/etcd/scheme.sh
  pkg/utils/informer/informer.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
  supported_releases.txt
  test/e2e/kwokctl/dryrun/testdata/binary/create_cluster.txt
  test/e2e/kwokctl/dryrun/testdata/binary/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/binary/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/docker/create_cluster.txt
  test/e2e/kwokctl/dryrun/testdata/docker/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/docker/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/kind-podman/create_cluster.txt
  test/e2e/kwokctl/dryrun/testdata/kind-podman/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/kind-podman/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/kind/create_cluster.txt
  test/e2e/kwokctl/dryrun/testdata/kind/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/kind/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/nerdctl/create_cluster.txt
  test/e2e/kwokctl/dryrun/testdata/nerdctl/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/nerdctl/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/podman/create_cluster.txt
  test/e2e/kwokctl/dryrun/testdata/podman/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/podman/create_cluster_with_verbosity.txt
  test/release/testdata/build-with-push-bucket-staging.txt
  test/release/testdata/build-with-push-bucket.txt
  test/release/testdata/build-with-push-ghrelease.txt
  test/release/testdata/build.txt
  test/release/testdata/cluster-image-nerdctl-with-push-staging.txt
  test/release/testdata/cluster-image-nerdctl-with-push.txt
  test/release/testdata/cluster-image-nerdctl.txt
  test/release/testdata/cluster-image-podman-with-push-staging.txt
  test/release/testdata/cluster-image-podman-with-push.txt
  test/release/testdata/cluster-image-podman.txt
  test/release/testdata/cluster-image-with-push-staging.txt
  test/release/testdata/cluster-image-with-push.txt
  test/release/testdata/cluster-image.txt
  test/release/testdata/cross-build-with-push-bucket-staging.txt
  test/release/testdata/cross-build-with-push-bucket.txt
  test/release/testdata/cross-build-with-push-ghrelease.txt
  test/release/testdata/cross-build.txt
  test/release/testdata/cross-cluster-image-nerdctl-with-push-staging.txt
  test/release/testdata/cross-cluster-image-nerdctl-with-push.txt
  test/release/testdata/cross-cluster-image-nerdctl.txt
  test/release/testdata/cross-cluster-image-podman-with-push-staging.txt
  test/release/testdata/cross-cluster-image-podman-with-push.txt
  test/release/testdata/cross-cluster-image-podman.txt
  test/release/testdata/cross-cluster-image-with-push-staging.txt
  test/release/testdata/cross-cluster-image-with-push.txt
  test/release/testdata/cross-cluster-image.txt
Labels: size/XL, approved, kind/cleanup, kind/documentation, cncf-cla: yes, release-note-none

#1375 [kwokctl] Fixed the default stage
  pkg/kwokctl/runtime/cluster.go
Labels: approved, kind/cleanup, cncf-cla: yes, size/M, release-note-none

#1380 Use watch instead list on pod sync
  charts/kwok/conf/kwok.yaml
  kustomize/kwok/kwok.yaml
Labels: kind/feature, approved, size/XS, cncf-cla: yes, release-note-none

#1382 Bump metrics-server to v0.7.2
  pkg/consts/consts.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
  test/e2e/kwokctl/dryrun/testdata/binary/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/docker/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/kind-podman/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/kind/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/nerdctl/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/podman/create_cluster_with_verbosity.txt
Labels: approved, kind/cleanup, kind/documentation, cncf-cla: yes, size/M, release-note-none

#1383 Bump jaeger to v1.69.0
  pkg/consts/consts.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
  test/e2e/kwokctl/dryrun/testdata/binary/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/docker/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/kind-podman/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/kind/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/nerdctl/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/podman/create_cluster_with_verbosity.txt
Labels: approved, kind/cleanup, kind/documentation, cncf-cla: yes, size/M, release-note-none

#1385 Bump kind to v0.27.0
  .dependencies.yaml
  hack/requirements.sh
  pkg/consts/consts.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
Labels: approved, kind/cleanup, kind/documentation, size/XS, cncf-cla: yes, release-note-none

#1384 Bump prometheus to v3.3.1
  pkg/consts/consts.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
  test/e2e/kwokctl/dryrun/testdata/binary/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/binary/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/docker/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/docker/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/kind-podman/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/kind-podman/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/kind/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/kind/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/nerdctl/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/nerdctl/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/podman/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/podman/create_cluster_with_verbosity.txt
Labels: approved, kind/cleanup, kind/documentation, cncf-cla: yes, size/M, release-note-none

#1388 [kwokctl] Fix set default metrics usage
  pkg/kwokctl/runtime/cluster.go
Labels: kind/bug, approved, cncf-cla: yes, size/M, release-note-none

#1391 Clean up dependencies
  .dependencies.yaml
  go.mod
  go.sum
  hack/tools/tools.go
  hack/update-codegen.sh
  hack/update-controllergen.sh
Labels: approved, kind/cleanup, cncf-cla: yes, release-note-none, size/L

#1392 Bump dependencies
  go.mod
  go.sum
Labels: approved, kind/cleanup, cncf-cla: yes, size/M, release-note-none

#1386 Release 0.7
  pkg/consts/consts.go
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes, release-note-none

#1394 Bump charts to 0.2.0
  charts/kwok/Chart.yaml
  charts/metrics-usage/Chart.yaml
  charts/stage-fast/Chart.yaml
  site/static/charts/index.yaml
Labels: approved, kind/cleanup, kind/documentation, cncf-cla: yes, size/M, release-note-none

#1395 Move to 0.8.0 alpha
  pkg/consts/consts.go
  site/content/en/docs/generated/kwokctl_create_cluster.md
  test/e2e/kwokctl/dryrun/testdata/binary/create_cluster.txt
  test/e2e/kwokctl/dryrun/testdata/binary/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/binary/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/docker/create_cluster.txt
  test/e2e/kwokctl/dryrun/testdata/docker/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/docker/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/kind-podman/create_cluster.txt
  test/e2e/kwokctl/dryrun/testdata/kind-podman/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/kind-podman/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/kind/create_cluster.txt
  test/e2e/kwokctl/dryrun/testdata/kind/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/kind/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/nerdctl/create_cluster.txt
  test/e2e/kwokctl/dryrun/testdata/nerdctl/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/nerdctl/create_cluster_with_verbosity.txt
  test/e2e/kwokctl/dryrun/testdata/podman/create_cluster.txt
  test/e2e/kwokctl/dryrun/testdata/podman/create_cluster_with_extra.txt
  test/e2e/kwokctl/dryrun/testdata/podman/create_cluster_with_verbosity.txt
Labels: approved, kind/cleanup, kind/documentation, cncf-cla: yes, size/M, release-note-none

#1402 Bump nerdctl to 2.1.2
  .github/workflows/test.yaml
Labels: approved, kind/cleanup, size/XS, cncf-cla: yes, release-note-none
